package ${application.corePackage}.model;

import javax.persistence.Column;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import ${application.corePackage}.model.AbstractTimestampEntity;

<#if application.hasAudit()>
import org.hibernate.envers.Audited;
</#if>
/* generated by JSetup ${JSetupVersion} :  at ${.now} */
@Entity
<#if application.hasAudit()>
@Audited
</#if>
@Table(name = "CUSTOMER_OWNER")
public class CustomerOwner extends AbstractTimestampEntity{
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;
		
	@Column(name = "LOGO")
	private String logo;  			
		
	@Column(name = "NAME")
	private String name;  			
		
	@Column(name = "CNPJ")
	private String cnpj;  			
		
	@Column(name = "PHONE_NUMBER")
	private String phoneNumber;  			
		
	@Column(name = "CORPORATE_NAME")
	private String corporateName;  			
	
		
	public  CustomerOwner() {
		
	}
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getLogo() {
		return logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getCnpj() {
		return cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}
	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	public String getCorporateName() {
		return corporateName;
	}

	public void setCorporateName(String corporateName) {
		this.corporateName = corporateName;
	}
	
}
