/* generated by JSetup ${JSetupVersion} :  at ${.now} */
package ${application.corePackage}.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;

import javax.persistence.*;
import java.io.Serial;
import java.io.Serializable;
<#if application.hasAudit()>
import org.hibernate.envers.Audited;
</#if>

<#if application.hasAudit()>
@Audited
</#if>
@Getter
@Data
@Builder
@AllArgsConstructor
@Entity
@Table(name = "TENANT")
public class Tenant implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;
		
	@Column(name = "LOGO")
	private String logo;  			
		
	@Column(name = "NAME")
	private String name;  			
		
	@Column(name = "CNPJ")
	private String cnpj;  			
		
	@Column(name = "PHONE_NUMBER")
	private String phoneNumber;  			
		
	@Column(name = "CORPORATE_NAME")
	private String corporateName;  			

	public  Tenant() {
		super();
	}
}
