// services
export const serviceList = [
  {
    id: "980d2c6a-e463-4ece-ac3a-df27366d6f06",
    icon: "Truck",
    title: "Fast Delivery",
    description: "Start from $10",
  },
  {
    id: "4d545fcc-4354-4197-80eb-04dbc49ea1ec",
    icon: "MoneyGuarantee",
    title: "Money Guarantee",
    description: "7 Days Back",
  },
  {
    id: "8b2af48c-48df-4c25-9eb5-c78ce2ea10f3",
    icon: "AlarmClock",
    title: "365 Days",
    description: "For free return",
  },
  {
    id: "f0edf86f-aa5e-4d32-8988-82aec06b2229",
    icon: "Payment",
    title: "Payment",
    description: "Secure system",
  },
  {
    id: "bda5241f-f3ec-4891-844f-84d911ec572c",
    icon: "OnlineSupport",
    title: "Online Support",
    description: "24/7 daily",
  },
];
export const dealOfTheWeekList = [
  {
    imgUrl: "/assets/images/products/rayban.png",
    brand: "Say Ban Sunglass",
    off: 50,
  },
  {
    imgUrl: "/assets/images/products/nike.png",
    brand: "Yike Shoe Air Max",
    off: 30,
  },
  {
    imgUrl: "/assets/images/products/apple-watch.png",
    brand: "Air Jordan",
    off: 40,
  },
  {
    imgUrl: "/assets/images/products/perfume.png",
    brand: "Perfume",
    off: 20,
  },
  {
    imgUrl: "/assets/images/products/rayban.png",
    brand: "Say Ban Sunglass",
    off: 50,
  },
  {
    imgUrl: "/assets/images/products/nike.png",
    brand: "Yike Shoe Air Max",
    off: 30,
  },
  {
    imgUrl: "/assets/images/products/apple-watch.png",
    brand: "Air Jordan",
    off: 40,
  },
  {
    imgUrl: "/assets/images/products/perfume.png",
    brand: "Perfume",
    off: 20,
  },
];
export const hotDealsData = [
  {
    expireDate: "Dec 5, 2024",
    productName: "Apple Watch Series 4 (Black)",
    imgUrl: "/assets/images/products/xiaomi-watch.png",
  },
  {
    expireDate: "Dec 5, 2024",
    productName: "Apple Watch Series 4 (Black)",
    imgUrl: "/assets/images/products/xiaomi-watch.png",
  },
  {
    expireDate: "Dec 5, 2024",
    productName: "Apple Watch Series 4 (Black)",
    imgUrl: "/assets/images/products/xiaomi-watch.png",
  },
];

// products
export const products = [
  {
    id: "56b18419-a114-4d73-8725-48fa10823479",
    slug: "smart-watch-black",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Smart watch black",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/chair-and-clothes.png",
    images: [
      "/assets/images/products/chair-and-clothes.png",
      "/assets/images/products/chair-and-clothes.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "9a6ab40e-9af4-442b-a6a1-8abef4b4eaf6",
    slug: "smart-watch-black",
    shop: {
      id: "7fac1170-61da-4cac-a163-ce1d41cf6434",
      slug: "word-wide-wishes",
      user: {
        id: "97b2d499-bbaf-4a58-bf94-c74ade65232b",
        email: "Janae64@gmail.com",
        phone: "566.945.9615 x349",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg",
        password: "8Hg3yVQZwqwnlIo",
        dateOfBirth: "2002-05-01T01:36:12.848Z",
        verified: true,
        name: {
          firstName: "Izabella",
          lastName: "Mraz",
        },
      },
      email: "Melisa24@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Smart watch black",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 15,
    thumbnail: "/assets/images/products/t-shirt3.png",
    images: [
      "/assets/images/products/t-shirt3.png",
      "/assets/images/products/t-shirt3.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "2317e010-8e7b-460a-8ece-f518a81fc4a1",
    slug: "smart-watch-black",
    shop: {
      id: "3656fa23-850b-4660-9c97-475a4afc1001",
      slug: "scarlett-beauty",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Vito.Parker@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Smart watch black",
    brand: null,
    price: 150,
    size: null,
    colors: [],
    discount: 28,
    thumbnail: "/assets/images/products/t-shirt4.png",
    images: [
      "/assets/images/products/t-shirt4.png",
      "/assets/images/products/t-shirt4.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "117e49e6-bc83-49aa-8b8b-c0632d897ad7",
    slug: "smart-watch-black",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Smart watch black",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 21,
    thumbnail: "/assets/images/products/t-shirt5.png",
    images: [
      "/assets/images/products/t-shirt5.png",
      "/assets/images/products/t-shirt5.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "bb2d992e-c05b-422f-a32a-d4c817424178",
    slug: "smart-watch-black",
    shop: {
      id: "ce3438d4-0cd6-40af-84a2-548646dece31",
      slug: "keyboard-kiosk",
      user: {
        id: "4b18055e-6d4b-462a-ad0c-0788a8661d17",
        email: "Madonna.Smith64@gmail.com",
        phone: "973-410-8783 x11144",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1102.jpg",
        password: "oeII0hwGlIpEr5r",
        dateOfBirth: "1944-01-02T12:38:11.087Z",
        verified: true,
        name: {
          firstName: "Ellis",
          lastName: "Purdy",
        },
      },
      email: "Dashawn71@hotmail.com",
      name: "Keyboard Kiosk",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-5.png",
      profilePicture: "/assets/images/faces/propic(4).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Smart watch black",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/chair-and-clothes.png",
    images: [
      "/assets/images/products/chair-and-clothes.png",
      "/assets/images/products/chair-and-clothes.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "e56c8d68-9cf7-4015-b697-b911e8d610fb",
    slug: "smart-watch-black",
    shop: {
      id: "26050baf-8792-4d79-9651-2d5c139327e4",
      slug: "cybershop",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Darby48@hotmail.com",
      name: "Cybershop",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-8.png",
      profilePicture: "/assets/images/faces/propic(7).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Smart watch black",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 21,
    thumbnail: "/assets/images/products/t-shirt4.png",
    images: [
      "/assets/images/products/t-shirt4.png",
      "/assets/images/products/t-shirt4.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "71082cc8-37b5-4ebf-bb15-1fd126675443",
    slug: "smart-watch-black",
    shop: {
      id: "7fac1170-61da-4cac-a163-ce1d41cf6434",
      slug: "word-wide-wishes",
      user: {
        id: "97b2d499-bbaf-4a58-bf94-c74ade65232b",
        email: "Janae64@gmail.com",
        phone: "566.945.9615 x349",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg",
        password: "8Hg3yVQZwqwnlIo",
        dateOfBirth: "2002-05-01T01:36:12.848Z",
        verified: true,
        name: {
          firstName: "Izabella",
          lastName: "Mraz",
        },
      },
      email: "Melisa24@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Smart watch black",
    brand: null,
    price: 150,
    size: null,
    colors: [],
    discount: 28,
    thumbnail: "/assets/images/products/t-shirt3.png",
    images: [
      "/assets/images/products/t-shirt3.png",
      "/assets/images/products/t-shirt3.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "be4b5218-16ed-420d-8cc5-8932d67cc2f0",
    slug: "smart-watch-black",
    shop: {
      id: "26050baf-8792-4d79-9651-2d5c139327e4",
      slug: "cybershop",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Darby48@hotmail.com",
      name: "Cybershop",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-8.png",
      profilePicture: "/assets/images/faces/propic(7).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Smart watch black",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 15,
    thumbnail: "/assets/images/products/t-shirt5.png",
    images: [
      "/assets/images/products/t-shirt5.png",
      "/assets/images/products/t-shirt5.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "42127101-ff17-4a57-b536-2f208bbacb43",
    slug: "smart-watch-black",
    shop: {
      id: "b15f575a-18ec-46f8-aed2-6af3e33af40f",
      slug: "anytime-buys",
      user: {
        id: "e9911347-19fa-4767-84a6-5a175169e381",
        email: "Dana.Gislason@yahoo.com",
        phone: "905-466-5099",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/337.jpg",
        password: "X6OF78hrYeb4QaR",
        dateOfBirth: "1944-09-06T09:50:48.269Z",
        verified: true,
        name: {
          firstName: "Carmelo",
          lastName: "Walker",
        },
      },
      email: "Bruce.Mosciski@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Smart watch black",
    brand: null,
    price: 299,
    size: null,
    colors: [],
    discount: 19,
    thumbnail: "/assets/images/products/chair-and-clothes.png",
    images: [
      "/assets/images/products/chair-and-clothes.png",
      "/assets/images/products/chair-and-clothes.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "647ea285-e9bc-4f76-bf4e-ee9c27009ba9",
    slug: "smart-watch-black",
    shop: {
      id: "26050baf-8792-4d79-9651-2d5c139327e4",
      slug: "cybershop",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Darby48@hotmail.com",
      name: "Cybershop",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-8.png",
      profilePicture: "/assets/images/faces/propic(7).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Smart watch black",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 21,
    thumbnail: "/assets/images/products/t-shirt3.png",
    images: [
      "/assets/images/products/t-shirt3.png",
      "/assets/images/products/t-shirt3.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "35f8886d-bad5-4091-8e23-6c5eb1539275",
    slug: "sunglass",
    shop: {
      id: "20d02eb4-b016-442b-a1b0-194cde0a18e5",
      slug: "keyboard-kiosk",
      user: {
        id: "23164ede-804b-4303-b859-47edcbd55ae9",
        email: "Dale_Spinka@gmail.com",
        phone: "282.437.4080 x2903",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/21.jpg",
        password: "Mawyo4_6CAuaoAT",
        dateOfBirth: "1962-10-21T22:08:36.203Z",
        verified: true,
        name: {
          firstName: "Adrienne",
          lastName: "Veum",
        },
      },
      email: "Narciso26@hotmail.com",
      name: "Keyboard Kiosk",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-5.png",
      profilePicture: "/assets/images/faces/propic(4).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Sunglass",
    brand: null,
    price: 150,
    size: null,
    colors: [],
    discount: 8,
    thumbnail: "/assets/images/products/imagegoggles.png",
    images: [
      "/assets/images/products/imagegoggles.png",
      "/assets/images/products/imagegoggles.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "6f763dfc-e7ae-478e-9730-73c4a62091cc",
    slug: "makeup",
    shop: {
      id: "477f452b-365a-4193-aa8d-0cf05dec0028",
      slug: "constant-shoppers",
      user: {
        id: "1eb8cfa9-e31b-4aad-a3a7-0dc356dcbfd2",
        email: "Nikita25@gmail.com",
        phone: "407-714-9427 x42619",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1086.jpg",
        password: "o_oUZqX6RYYsjT5",
        dateOfBirth: "1997-03-24T02:30:58.468Z",
        verified: true,
        name: {
          firstName: "Regan",
          lastName: "Greenfelder",
        },
      },
      email: "Zack_Wolf@hotmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Makeup",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 8,
    thumbnail: "/assets/images/products/lipstick (2).png",
    images: [
      "/assets/images/products/lipstick (2).png",
      "/assets/images/products/lipstick (2).png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "77305e01-0d53-4932-b222-03278969438c",
    slug: "smart-watch",
    shop: {
      id: "71251019-56f9-4958-b7c5-a21b823240bf",
      slug: "coveted-clicks",
      user: {
        id: "0a107c08-3d13-4289-92b2-0867e6ab381a",
        email: "Domenica_Vandervort@gmail.com",
        phone: "(667) 676-2962 x4991",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1240.jpg",
        password: "3Rrb4p5YlcvMu1T",
        dateOfBirth: "1990-03-25T13:46:14.158Z",
        verified: true,
        name: {
          firstName: "Solon",
          lastName: "Prohaska",
        },
      },
      email: "Blair46@hotmail.com",
      name: "Coveted Clicks",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-3.png",
      profilePicture: "/assets/images/faces/propic(2).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Smart Watch",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 10,
    thumbnail: "/assets/images/products/bgwatch.png",
    images: [
      "/assets/images/products/bgwatch.png",
      "/assets/images/products/bgwatch.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "c553927c-93e5-4191-a4e8-022d8ad04800",
    slug: "lipstick",
    shop: {
      id: "41dd75bc-1124-4620-9202-282f6f1842e7",
      slug: "scarlett-beauty",
      user: {
        id: "d7adc359-a7ea-40ac-8858-2f2abe0b766b",
        email: "Bart20@gmail.com",
        phone: "537.724.6226 x56884",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/904.jpg",
        password: "6b2QX_ePRnWZTfQ",
        dateOfBirth: "1979-06-21T07:21:11.362Z",
        verified: true,
        name: {
          firstName: "Amya",
          lastName: "Larkin",
        },
      },
      email: "Noelia.OReilly8@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Lipstick",
    brand: null,
    price: 15,
    size: null,
    colors: [],
    discount: 5,
    thumbnail: "/assets/images/products/lipstick (1).png",
    images: [
      "/assets/images/products/lipstick (1).png",
      "/assets/images/products/lipstick (1).png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "c0f5ec1d-ef16-4475-9748-448b5b55bb38",
    slug: "green-plant",
    shop: {
      id: "41dd75bc-1124-4620-9202-282f6f1842e7",
      slug: "scarlett-beauty",
      user: {
        id: "d7adc359-a7ea-40ac-8858-2f2abe0b766b",
        email: "Bart20@gmail.com",
        phone: "537.724.6226 x56884",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/904.jpg",
        password: "6b2QX_ePRnWZTfQ",
        dateOfBirth: "1979-06-21T07:21:11.362Z",
        verified: true,
        name: {
          firstName: "Amya",
          lastName: "Larkin",
        },
      },
      email: "Noelia.OReilly8@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Green plant",
    brand: null,
    price: 55,
    size: null,
    colors: [],
    discount: 7,
    thumbnail: "/assets/images/products/lipstick (4).png",
    images: [
      "/assets/images/products/lipstick (4).png",
      "/assets/images/products/lipstick (4).png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 2,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "e3de3994-2261-4e00-987b-00ce5058a6a3",
    slug: "bonsai-tree",
    shop: {
      id: "20d02eb4-b016-442b-a1b0-194cde0a18e5",
      slug: "keyboard-kiosk",
      user: {
        id: "23164ede-804b-4303-b859-47edcbd55ae9",
        email: "Dale_Spinka@gmail.com",
        phone: "282.437.4080 x2903",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/21.jpg",
        password: "Mawyo4_6CAuaoAT",
        dateOfBirth: "1962-10-21T22:08:36.203Z",
        verified: true,
        name: {
          firstName: "Adrienne",
          lastName: "Veum",
        },
      },
      email: "Narciso26@hotmail.com",
      name: "Keyboard Kiosk",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-5.png",
      profilePicture: "/assets/images/faces/propic(4).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Bonsai tree",
    brand: null,
    price: 535,
    size: null,
    colors: [],
    discount: 6,
    thumbnail: "/assets/images/products/lipstick (3).png",
    images: [
      "/assets/images/products/lipstick (3).png",
      "/assets/images/products/lipstick (3).png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "fe987c24-6205-4add-b009-72fe2f6dfff9",
    slug: "smart-watch",
    shop: {
      id: "7a671540-eec4-4c4e-a052-b5eceaf388e6",
      slug: "scroll-through",
      user: {
        id: "1eb8cfa9-e31b-4aad-a3a7-0dc356dcbfd2",
        email: "Nikita25@gmail.com",
        phone: "407-714-9427 x42619",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1086.jpg",
        password: "o_oUZqX6RYYsjT5",
        dateOfBirth: "1997-03-24T02:30:58.468Z",
        verified: true,
        name: {
          firstName: "Regan",
          lastName: "Greenfelder",
        },
      },
      email: "Hilma35@hotmail.com",
      name: "Scroll Through",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner.png",
      profilePicture: "/assets/images/faces/propic(1).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Smart Watch",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 10,
    thumbnail: "/assets/images/products/bgwatch.png",
    images: [
      "/assets/images/products/bgwatch.png",
      "/assets/images/products/bgwatch.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "5a05433b-ec71-4dba-9ba7-ebfcac52e191",
    slug: "green-plant",
    shop: {
      id: "71251019-56f9-4958-b7c5-a21b823240bf",
      slug: "coveted-clicks",
      user: {
        id: "0a107c08-3d13-4289-92b2-0867e6ab381a",
        email: "Domenica_Vandervort@gmail.com",
        phone: "(667) 676-2962 x4991",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1240.jpg",
        password: "3Rrb4p5YlcvMu1T",
        dateOfBirth: "1990-03-25T13:46:14.158Z",
        verified: true,
        name: {
          firstName: "Solon",
          lastName: "Prohaska",
        },
      },
      email: "Blair46@hotmail.com",
      name: "Coveted Clicks",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-3.png",
      profilePicture: "/assets/images/faces/propic(2).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Green plant",
    brand: null,
    price: 55,
    size: null,
    colors: [],
    discount: 7,
    thumbnail: "/assets/images/products/lipstick (4).png",
    images: [
      "/assets/images/products/lipstick (4).png",
      "/assets/images/products/lipstick (4).png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 2,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "a7caf4ab-f9b6-4077-885a-7fe253243e0d",
    slug: "asus-rog-strix-g15",
    shop: {
      id: "84c3d794-6ba0-4348-a6bb-ee69e26ddbfa",
      slug: "cybershop",
      user: {
        id: "f2be379d-7f7b-4633-973a-283da1a26888",
        email: "Lynn.Durgan79@hotmail.com",
        phone: "786.821.4214 x19707",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/657.jpg",
        password: "3ErHZcPGPQqbMjf",
        dateOfBirth: "1957-06-16T13:17:36.990Z",
        verified: true,
        name: {
          firstName: "Connor",
          lastName: "Bernhard",
        },
      },
      email: "Keenan.Muller29@yahoo.com",
      name: "Cybershop",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-8.png",
      profilePicture: "/assets/images/faces/propic(7).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "ASUS ROG Strix G15",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 56,
    thumbnail: "/assets/images/products/long-product.png",
    images: [
      "/assets/images/products/long-product.png",
      "/assets/images/products/long-product.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "b1727327-e5c1-480d-8bcb-f2f37c6596f0",
    slug: "asus-rog-strix-g15",
    shop: {
      id: "0c15ca44-426f-4d94-9ef0-2b2531fc77a3",
      slug: "keyboard-kiosk",
      user: {
        id: "f479f676-c09a-4a80-bed8-441673bbc009",
        email: "Jamar84@yahoo.com",
        phone: "252.203.7788 x91709",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/329.jpg",
        password: "0dhEMVxLHj_vBOc",
        dateOfBirth: "2000-04-06T02:56:04.206Z",
        verified: true,
        name: {
          firstName: "Jacky",
          lastName: "Mante",
        },
      },
      email: "Rocky92@hotmail.com",
      name: "Keyboard Kiosk",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-5.png",
      profilePicture: "/assets/images/faces/propic(4).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "ASUS ROG Strix G15",
    brand: null,
    price: 140,
    size: null,
    colors: [],
    discount: 23,
    thumbnail: "/assets/images/products/shoe.png",
    images: [
      "/assets/images/products/shoe.png",
      "/assets/images/products/shoe.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "7b0dc43d-9b16-498b-b70b-964063f809ea",
    slug: "asus-rog-strix-g15",
    shop: {
      id: "0c15ca44-426f-4d94-9ef0-2b2531fc77a3",
      slug: "keyboard-kiosk",
      user: {
        id: "f479f676-c09a-4a80-bed8-441673bbc009",
        email: "Jamar84@yahoo.com",
        phone: "252.203.7788 x91709",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/329.jpg",
        password: "0dhEMVxLHj_vBOc",
        dateOfBirth: "2000-04-06T02:56:04.206Z",
        verified: true,
        name: {
          firstName: "Jacky",
          lastName: "Mante",
        },
      },
      email: "Rocky92@hotmail.com",
      name: "Keyboard Kiosk",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-5.png",
      profilePicture: "/assets/images/faces/propic(4).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "ASUS ROG Strix G15",
    brand: null,
    price: 200,
    size: null,
    colors: [],
    discount: 42,
    thumbnail: "/assets/images/products/t-shirt3.png",
    images: [
      "/assets/images/products/t-shirt3.png",
      "/assets/images/products/t-shirt3.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "f9fde838-ae08-44de-8833-839b6b22739d",
    slug: "asus-rog-strix-g15",
    shop: {
      id: "84c3d794-6ba0-4348-a6bb-ee69e26ddbfa",
      slug: "cybershop",
      user: {
        id: "f2be379d-7f7b-4633-973a-283da1a26888",
        email: "Lynn.Durgan79@hotmail.com",
        phone: "786.821.4214 x19707",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/657.jpg",
        password: "3ErHZcPGPQqbMjf",
        dateOfBirth: "1957-06-16T13:17:36.990Z",
        verified: true,
        name: {
          firstName: "Connor",
          lastName: "Bernhard",
        },
      },
      email: "Keenan.Muller29@yahoo.com",
      name: "Cybershop",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-8.png",
      profilePicture: "/assets/images/faces/propic(7).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "ASUS ROG Strix G15",
    brand: null,
    price: 450,
    size: null,
    colors: [],
    discount: 39,
    thumbnail: "/assets/images/products/t-shirt4.png",
    images: [
      "/assets/images/products/t-shirt4.png",
      "/assets/images/products/t-shirt4.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "315326d3-b2b5-47cf-ad89-dcbf9aa1e022",
    slug: "asus-rog-strix-g15",
    shop: {
      id: "0c15ca44-426f-4d94-9ef0-2b2531fc77a3",
      slug: "keyboard-kiosk",
      user: {
        id: "f479f676-c09a-4a80-bed8-441673bbc009",
        email: "Jamar84@yahoo.com",
        phone: "252.203.7788 x91709",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/329.jpg",
        password: "0dhEMVxLHj_vBOc",
        dateOfBirth: "2000-04-06T02:56:04.206Z",
        verified: true,
        name: {
          firstName: "Jacky",
          lastName: "Mante",
        },
      },
      email: "Rocky92@hotmail.com",
      name: "Keyboard Kiosk",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-5.png",
      profilePicture: "/assets/images/faces/propic(4).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "ASUS ROG Strix G15",
    brand: null,
    price: 750,
    size: null,
    colors: [],
    discount: 24,
    thumbnail: "/assets/images/products/t-shirt5.png",
    images: [
      "/assets/images/products/t-shirt5.png",
      "/assets/images/products/t-shirt5.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 1,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "946c6cf7-fd8d-4a60-9a7c-f5055a70b450",
    slug: "asus-rog-strix-g15",
    shop: {
      id: "84c3d794-6ba0-4348-a6bb-ee69e26ddbfa",
      slug: "cybershop",
      user: {
        id: "f2be379d-7f7b-4633-973a-283da1a26888",
        email: "Lynn.Durgan79@hotmail.com",
        phone: "786.821.4214 x19707",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/657.jpg",
        password: "3ErHZcPGPQqbMjf",
        dateOfBirth: "1957-06-16T13:17:36.990Z",
        verified: true,
        name: {
          firstName: "Connor",
          lastName: "Bernhard",
        },
      },
      email: "Keenan.Muller29@yahoo.com",
      name: "Cybershop",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-8.png",
      profilePicture: "/assets/images/faces/propic(7).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "ASUS ROG Strix G15",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 56,
    thumbnail: "/assets/images/products/chair-and-clothes.png",
    images: [
      "/assets/images/products/chair-and-clothes.png",
      "/assets/images/products/chair-and-clothes.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "fdf573ed-241c-4a77-aff0-2e8aa5773f6c",
    slug: "asus-rog-strix-g15",
    shop: {
      id: "19f49f5d-50e5-4d30-ae0c-7420874af8ca",
      slug: "word-wide-wishes",
      user: {
        id: "275377cc-155c-41f6-8f71-eb774d59ca3d",
        email: "Jaquan.Frami@yahoo.com",
        phone: "854-768-1285",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/325.jpg",
        password: "ynlLfTXF2xKDCS4",
        dateOfBirth: "1983-03-29T09:19:15.395Z",
        verified: true,
        name: {
          firstName: "Aliyah",
          lastName: "Bartoletti",
        },
      },
      email: "Bret_Brakus@gmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "ASUS ROG Strix G15",
    brand: null,
    price: 299,
    size: null,
    colors: [],
    discount: 54,
    thumbnail: "/assets/images/products/t-shirt4.png",
    images: [
      "/assets/images/products/t-shirt4.png",
      "/assets/images/products/t-shirt4.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
];
