- name: HistoricoConfiguracaoGestor
  displayName: Historico configuracao gestor
  tableName: HISTORICO_CONFIGURACAO_GESTOR
  pk: ID_HISTORICO_CONFIGURACAO_GESTOR
  sequence: GSH_SEQ_HISTORICO_CONFIGURACAO_GESTOR
  attributes:                     
  - name: dataHora
    tableFieldName: DATA_HORA
    required: false
    displayName: DATA HORA
    type: 
      className: Datetime
  - name: usuario
    tableFieldName: USUARIO
    required: false
    displayName: USUARIO
    type: 
      className: String
  relationships:                     
  - name: configuracaoGestor             
    type: ManyToOne
    model: ConfiguracaoGestor                       
    displayName: CONFIGURACAO GESTOR
    fk:   ID_CONFIGURACAO_GESTOR
    viewApproach:   
      type: modal 
      hiddenField: id 
      textField: descricao 
  - name: acaoRealizada             
    type: ManyToOne
    model: AcaoRealizada                       
    displayName: ACAO REALIZADA
    fk:   ID_ACAO_REALIZADA
    viewApproach:   
      type: modal 
      hiddenField: id 
      textField: descricao 
