- name: ConfiguracaoGestor
  displayName: Configuracao gestor
  tableName: CONFIGURACAO_GESTOR
  pk: ID_CONFIGURACAO_GESTOR
  sequence: GSH_SEQ_CONFIGURACAO_GESTOR
  attributes:                     
  - name: nomeSecretario
    tableFieldName: NOME_SECRETARIO
    required: false
    displayName: Nome do Secretário
    type: 
      className: String
  - name: nomeFiscal
    tableFieldName: NOME_FISCAL
    required: false
    displayName: Nome do Fiscal
    type: 
      className: String
  - name: descricaoJustificativa
    tableFieldName: DESCRICAO_JUSTIFICATIVA
    required: false
    displayName: Justificativa
    type: 
      className: String
