// carousel data
export const mainCarouselData = [
  {
    id: 1,
    title: "Lifestyle collection",
    category: "Men",
    discount: 30,
    imgUrl: "/assets/images/banners/banner-15.jpg",
    description: "Get Free Shipping on orders over $99.00",
    buttonText: "Shop Now",
    buttonLink: "#",
  },
  {
    id: 2,
    title: "Lifestyle collection",
    category: "Women",
    discount: 35,
    imgUrl: "/assets/images/banners/banner-25.jpg",
    description: "Get Free Shipping on orders over $99.00",
    buttonText: "Shop Now",
    buttonLink: "#",
  },
];

// categories
export const categories = [
  {
    id: "51cc79e6-c0d8-40e6-b9a5-a3a0c5931242",
    name: "Toys",
    icon: null,
    image: "/assets/images/categories/cat-1.jpg",
    slug: "toys",
    parent: [],
    description: null,
    for: {
      demo: "market-2",
      type: "top-categories",
    },
  },
  {
    id: "c1a775f6-7bc5-4722-9c2e-841cae78b93c",
    name: "Sports",
    icon: null,
    image: "/assets/images/categories/cat-2.jpg",
    slug: "sports",
    parent: [],
    description: null,
    for: {
      demo: "market-2",
      type: "top-categories",
    },
  },
  {
    id: "dc829abb-9667-4d59-ad2b-5ef455202188",
    name: "Gaming",
    icon: null,
    image: "/assets/images/categories/cat-3.jpg",
    slug: "gaming",
    parent: [],
    description: null,
    for: {
      demo: "market-2",
      type: "top-categories",
    },
  },
  {
    id: "9c35917b-c0c6-4583-9145-6285b50b49ad",
    name: "Furniture",
    icon: null,
    image: "/assets/images/categories/cat-4.jpg",
    slug: "furniture",
    parent: [],
    description: null,
    for: {
      demo: "market-2",
      type: "top-categories",
    },
  },
  {
    id: "e13157eb-e9c5-4a24-a59b-98382b7eb3ea",
    name: "Fashion",
    icon: null,
    image: "/assets/images/categories/cat-5.jpg",
    slug: "fashion",
    parent: [],
    description: null,
    for: {
      demo: "market-2",
      type: "top-categories",
    },
  },
  {
    id: "c71a65bd-5c01-444e-82fe-3ef09462aff6",
    name: "Cameras",
    icon: null,
    image: "/assets/images/categories/cat-6.jpg",
    slug: "cameras",
    parent: [],
    description: null,
    for: {
      demo: "market-2",
      type: "top-categories",
    },
  },
];

// products
export const products = [
  {
    id: "6e8f151b-277b-4465-97b6-547f6a72e5c9",
    slug: "silver-high-neck-sweater",
    shop: {
      id: "d3a8d0c3-ea4d-4caa-858e-954fee09ff24",
      slug: "scarlett-beauty",
      user: {
        id: "ba29997c-ed76-4f59-ae31-111dfa532b75",
        email: "Clementina_Raynor@yahoo.com",
        phone: "821.333.9362 x9878",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1006.jpg",
        password: "673_HVvWUdYguFe",
        dateOfBirth: "2003-06-14T15:18:27.382Z",
        verified: true,
        name: {
          firstName: "Aracely",
          lastName: "Doyle",
        },
      },
      email: "Amira.McDermott83@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Silver High Neck Sweater",
    brand: null,
    price: 210,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/1.SilverHighNeckSweater.png",
    images: [
      "/assets/images/products/Fashion/Clothes/1.SilverHighNeckSweater.png",
      "/assets/images/products/Fashion/Clothes/1.SilverHighNeckSweater.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    for: {
      demo: "market-2",
      type: "deals-of-the-day",
    },
  },
  {
    id: "76d14d65-21d0-4b41-8ee1-eef4c2232793",
    slug: "yellow-casual-sweater",
    shop: {
      id: "d3a8d0c3-ea4d-4caa-858e-954fee09ff24",
      slug: "scarlett-beauty",
      user: {
        id: "ba29997c-ed76-4f59-ae31-111dfa532b75",
        email: "Clementina_Raynor@yahoo.com",
        phone: "821.333.9362 x9878",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1006.jpg",
        password: "673_HVvWUdYguFe",
        dateOfBirth: "2003-06-14T15:18:27.382Z",
        verified: true,
        name: {
          firstName: "Aracely",
          lastName: "Doyle",
        },
      },
      email: "Amira.McDermott83@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Yellow Casual Sweater",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/21.YellowCasualSweater.png",
    images: [
      "/assets/images/products/Fashion/Clothes/21.YellowCasualSweater.png",
      "/assets/images/products/Fashion/Clothes/21.YellowCasualSweater.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    for: {
      demo: "market-2",
      type: "deals-of-the-day",
    },
  },
  {
    id: "0fffb188-98d8-47f7-8189-254f06cad488",
    slug: "denim-blue-jeans",
    shop: {
      id: "d3a8d0c3-ea4d-4caa-858e-954fee09ff24",
      slug: "scarlett-beauty",
      user: {
        id: "ba29997c-ed76-4f59-ae31-111dfa532b75",
        email: "Clementina_Raynor@yahoo.com",
        phone: "821.333.9362 x9878",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1006.jpg",
        password: "673_HVvWUdYguFe",
        dateOfBirth: "2003-06-14T15:18:27.382Z",
        verified: true,
        name: {
          firstName: "Aracely",
          lastName: "Doyle",
        },
      },
      email: "Amira.McDermott83@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Denim Blue Jeans",
    brand: null,
    price: 140,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/Fashion/Clothes/4.DenimBlueJeans.png",
    images: [
      "/assets/images/products/Fashion/Clothes/4.DenimBlueJeans.png",
      "/assets/images/products/Fashion/Clothes/4.DenimBlueJeans.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    for: {
      demo: "market-2",
      type: "deals-of-the-day",
    },
  },
  {
    id: "fb0a22ee-dbae-4ca0-87cf-a2fdde344dec",
    slug: "black-white-sweater",
    shop: {
      id: "d3a8d0c3-ea4d-4caa-858e-954fee09ff24",
      slug: "scarlett-beauty",
      user: {
        id: "ba29997c-ed76-4f59-ae31-111dfa532b75",
        email: "Clementina_Raynor@yahoo.com",
        phone: "821.333.9362 x9878",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1006.jpg",
        password: "673_HVvWUdYguFe",
        dateOfBirth: "2003-06-14T15:18:27.382Z",
        verified: true,
        name: {
          firstName: "Aracely",
          lastName: "Doyle",
        },
      },
      email: "Amira.McDermott83@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Black White Sweater",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/19.BlackWhiteSweater.png",
    images: [
      "/assets/images/products/Fashion/Clothes/19.BlackWhiteSweater.png",
      "/assets/images/products/Fashion/Clothes/19.BlackWhiteSweater.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    for: {
      demo: "market-2",
      type: "deals-of-the-day",
    },
  },
  {
    id: "94452fd4-89fb-426e-b90e-db955517d167",
    slug: "gray-overcoat-women",
    shop: {
      id: "14f0aa30-b962-47e4-aab9-b6b9b40f3d6c",
      slug: "scroll-through",
      user: {
        id: "dea7c262-0866-4fa7-a92a-0327e204d010",
        email: "Fausto.Schowalter@gmail.com",
        phone: "859-699-8461 x50403",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1048.jpg",
        password: "1qfhl8ZZ88W6ain",
        dateOfBirth: "1974-02-27T05:00:31.895Z",
        verified: true,
        name: {
          firstName: "Dan",
          lastName: "Purdy",
        },
      },
      email: "Jayce_Corkery32@gmail.com",
      name: "Scroll Through",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner.png",
      profilePicture: "/assets/images/faces/propic(1).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Gray Overcoat Women",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/20.GrayOvercoatWomen.png",
    images: [
      "/assets/images/products/Fashion/Clothes/20.GrayOvercoatWomen.png",
      "/assets/images/products/Fashion/Clothes/20.GrayOvercoatWomen.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    for: {
      demo: "market-2",
      type: "deals-of-the-day",
    },
  },
  {
    id: "c5aa31dc-56db-4328-b3de-ad9383510405",
    slug: "women's-fashion",
    shop: {
      id: "ab657fb2-89c6-4f1e-b034-6bebfc3d864c",
      slug: "word-wide-wishes",
      user: {
        id: "d1d88484-5ec0-4d53-b394-6b7cbc1f6440",
        email: "Marlin63@gmail.com",
        phone: "(700) 338-5159 x24398",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1124.jpg",
        password: "GwaFEehjyCfdvxR",
        dateOfBirth: "1967-07-25T08:37:16.955Z",
        verified: true,
        name: {
          firstName: "Sharon",
          lastName: "Lebsack",
        },
      },
      email: "Mortimer28@gmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Women's Fashion",
    brand: null,
    price: 140,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
    images: [
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
    ],
    categories: ["Fashion"],
    status: null,
    reviews: [],
    for: {
      demo: "market-2",
      type: "deals-of-the-day",
    },
  },
  {
    id: "4b687a8d-2d14-4724-9f07-f550e582c3ca",
    slug: "nike-red",
    shop: {
      id: "ac69bc02-6218-4e73-a1d7-637bb80d8546",
      slug: "constant-shoppers",
      user: {
        id: "ba29997c-ed76-4f59-ae31-111dfa532b75",
        email: "Clementina_Raynor@yahoo.com",
        phone: "821.333.9362 x9878",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1006.jpg",
        password: "673_HVvWUdYguFe",
        dateOfBirth: "2003-06-14T15:18:27.382Z",
        verified: true,
        name: {
          firstName: "Aracely",
          lastName: "Doyle",
        },
      },
      email: "Salvatore26@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Red",
    brand: null,
    price: 210,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/Fashion/Shoes/1.Nike Red.png",
    images: [
      "/assets/images/products/Fashion/Shoes/1.Nike Red.png",
      "/assets/images/products/Fashion/Shoes/1.Nike Red.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    for: {
      demo: "market-2",
      type: "deals-of-the-day",
    },
  },
  {
    id: "d0dd72e2-8624-4792-8248-8cc1d2d913c9",
    slug: "north-star-blue",
    shop: {
      id: "a02892b3-c442-49d4-8ac1-24fede12a300",
      slug: "anytime-buys",
      user: {
        id: "366ee083-9219-47fa-a4b6-dff04ec010cf",
        email: "Junius.Farrell@gmail.com",
        phone: "558.717.4898 x4537",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/520.jpg",
        password: "IszXJOR5PSVUckz",
        dateOfBirth: "1989-09-12T14:49:00.812Z",
        verified: true,
        name: {
          firstName: "Dee",
          lastName: "Lynch",
        },
      },
      email: "Furman_Schneider@gmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "North Star Blue",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/Fashion/Shoes/21.NorthStarBlue.png",
    images: [
      "/assets/images/products/Fashion/Shoes/21.NorthStarBlue.png",
      "/assets/images/products/Fashion/Shoes/21.NorthStarBlue.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    for: {
      demo: "market-2",
      type: "deals-of-the-day",
    },
  },
];

// services
export const serviceList = [
  {
    id: "ee272e30-0309-4e8a-966c-f63410c58289",
    icon: "Truck",
    title: "Fast Delivery",
    description: "Start from $10",
  },
  {
    id: "1f30c35b-5b76-42c0-822f-83ecbfb64869",
    icon: "MoneyGuarantee",
    title: "Money Guarantee",
    description: "7 Days Back",
  },
  {
    id: "a4c3968e-93ba-444b-a68f-2e6dd9a5eb1a",
    icon: "AlarmClock",
    title: "365 Days",
    description: "For free return",
  },
  {
    id: "87379ae9-5e25-4d53-8d7d-7cc3f971dd67",
    icon: "Payment",
    title: "Payment",
    description: "Secure system",
  },
];

// single category data
export const singleCategory = {
  title: "Electronic",
  children: [
    "Wireless Speaker",
    "Tablet",
    "Smartphone",
    "Laptop",
    "iMac",
    "Game Controller",
    "Drone",
    "Apple",
  ],
};

// brands
export const brandList = [
  {
    id: "9aee1898-23e0-4965-8f0d-427dc963ae07",
    slug: "alibaba",
    name: "AliBaba",
    image: "/assets/images/brands/alibaba.png",
    type: "fashion",
    for: {
      demo: "market-2",
      type: "top-brands",
    },
  },
  {
    id: "024ec2a2-7ca7-46c2-8990-f78ac4215dd1",
    slug: "levis",
    name: "Levis",
    image: "/assets/images/brands/levis.png",
    type: "fashion",
    for: {
      demo: "market-2",
      type: "top-brands",
    },
  },
  {
    id: "e370f16a-90e2-4f26-b9af-a38d6f645a4c",
    slug: "lotto",
    name: "Lotto",
    image: "/assets/images/brands/lotto.png",
    type: "fashion",
    for: {
      demo: "market-2",
      type: "top-brands",
    },
  },
  {
    id: "d8f4c60e-6bac-4fdc-9880-999fbddac97d",
    slug: "raymond",
    name: "Raymond",
    image: "/assets/images/brands/raymond.png",
    type: "fashion",
    for: {
      demo: "market-2",
      type: "top-brands",
    },
  },
  {
    id: "0c74cb7c-6082-4640-9380-815928be7127",
    slug: "samsung",
    name: "Samsung",
    image: "/assets/images/brands/samsung.png",
    type: "fashion",
    for: {
      demo: "market-2",
      type: "top-brands",
    },
  },
];
