/* Application Router  generated by JSetup v0.95 :  at 23/08/2018 22:12:07 */
import React from 'react';
import { HashRouter as Router, Route, Switch } from 'react-router-dom';

import FormFilme from '../components/filme/FormFilme'
import PageFilme from '../components/filme/PageFilme'
import FormClassificacao from '../components/classificacao/FormClassificacao'
import PageClassificacao from '../components/classificacao/PageClassificacao'
import FormUser from '../components/user/FormUser'
import PageUser from '../components/user/PageUser'
import FormRole from '../components/role/FormRole'
import PageRole from '../components/role/PageRole'
import FormPermission from '../components/permission/FormPermission'
import PagePermission from '../components/permission/PagePermission'
import FormGroup from '../components/group/FormGroup'
import PageGroup from '../components/group/PageGroup'
import FormItem from '../components/item/FormItem'
import PageItem from '../components/item/PageItem'

const Root = () => {
  return (
    <Router>
      <div>
         <Route path="/filmes/edit/:id" component={FormFilme} exact />
         <Route path="/filmes/new" component={FormFilme} exact />
         <Route path="/filmes/list" component={PageFilme} exact />
         <Route path="/classificacaos/edit/:id" component={FormClassificacao} exact />
         <Route path="/classificacaos/new" component={FormClassificacao} exact />
         <Route path="/classificacaos/list" component={PageClassificacao} exact />
         <Route path="/users/edit/:id" component={FormUser} exact />
         <Route path="/users/new" component={FormUser} exact />
         <Route path="/users/list" component={PageUser} exact />
         <Route path="/roles/edit/:id" component={FormRole} exact />
         <Route path="/roles/new" component={FormRole} exact />
         <Route path="/roles/list" component={PageRole} exact />
         <Route path="/permissions/edit/:id" component={FormPermission} exact />
         <Route path="/permissions/new" component={FormPermission} exact />
         <Route path="/permissions/list" component={PagePermission} exact />
         <Route path="/groups/edit/:id" component={FormGroup} exact />
         <Route path="/groups/new" component={FormGroup} exact />
         <Route path="/groups/list" component={PageGroup} exact />
         <Route path="/items/edit/:id" component={FormItem} exact />
         <Route path="/items/new" component={FormItem} exact />
         <Route path="/items/list" component={PageItem} exact />
      </div>
    </Router>
  );
};

export default Root;

