// categories for sales-1
export const categories = [
  {
    id: "ecc42ce0-f941-4702-8c53-c822e4b8178c",
    name: "Furniture",
    icon: "Sofa",
    image: null,
    slug: "furniture",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "d0f90d4f-46a5-495a-a24f-ee82734eb703",
    name: "Women",
    icon: "WomenDress",
    image: null,
    slug: "women",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "96a7bd22-c97e-4c07-aa70-56fe7dbdc3ec",
    name: "Electronics",
    icon: "Camera",
    image: null,
    slug: "electronics",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "431009f1-1e32-4038-8b8e-be3cc9dc1c86",
    name: "Cosmetics",
    icon: "BeautyProducts",
    image: null,
    slug: "cosmetics",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
];

// categories for sales-2
export const categoriesTwo = [
  {
    id: "5cff024a-d7fd-4b58-a8ab-ecb6638be74b",
    name: "Men",
    icon: "Tshirt",
    image: null,
    slug: "men",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "3a35ea11-4791-4477-8ced-18437d421ee2",
    name: "Photos",
    icon: "Picture",
    image: null,
    slug: "photos",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "efbff951-9b59-436a-90e0-b92c37bf464f",
    name: "Clothes",
    icon: "Tshirt",
    image: null,
    slug: "clothes",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "740e1b21-8540-4180-b425-71146ea28d59",
    name: "Furniture",
    icon: "Sofa",
    image: null,
    slug: "furniture",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "d3415086-c10f-4490-aec0-90cf72a4e69d",
    name: "Sport",
    icon: "BasketBall",
    image: null,
    slug: "sport",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "83c499b4-3b13-4927-bf75-eae73cd5eff4",
    name: "Women",
    icon: "WomenDress",
    image: null,
    slug: "women",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "750ea9c1-0f6a-484b-adef-f1308a7b371b",
    name: "Automobile",
    icon: "Wheel",
    image: null,
    slug: "automobile",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "fa369f93-05d4-4109-8910-072cdff145db",
    name: "Accessories",
    icon: "Watch",
    image: null,
    slug: "accessories",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "2ea44194-cd3a-48fb-a713-c0eb5aa6514b",
    name: "Eelctronics",
    icon: "Camera",
    image: null,
    slug: "eelctronics",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "92510257-fcd9-4397-bed4-2149fa252709",
    name: "Hardware",
    icon: "DrillMachine",
    image: null,
    slug: "hardware",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "48266ecb-94c8-4877-be19-92af85ddfe03",
    name: "Cosmetics",
    icon: "BeautyProducts",
    image: null,
    slug: "cosmetics",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
  {
    id: "9f1e7a55-7ae4-462e-9b9e-f31a8efad0f1",
    name: "Baby products",
    icon: "BabyFeeder",
    image: null,
    slug: "baby-products",
    parent: [],
    description: null,
    for: {
      demo: "sale-page-1",
      type: "categories",
    },
  },
];
