<!-- generated by JSetup ${JSetupVersion} :  at ${.now} -->
<!-- Begin ${entity.name}´s page -->
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12">
		<did id="container${entity.name}s">
	</div>
</div>
<div style="position: fixed; display: block; z-index: 9; bottom: 10px; right: 10px;"  id="floatButton"></div>
 
<!-- End ${entity.name}´s page -->