<!-- Filme´s form generated by JSetup v0.95 :  at 04/01/2018 19:39:25  -->
<template>
<div class="panel">
	<div class="panel-heading">
		<h3 class="panel-title">Cadastro de Filme</h3>
	</div>
	<div class="panel-body">
		<div class="panel">
			<div class="panel-body">
				<div id="messages_div"></div>
				<form role="form">
					<input type="hidden" id="inputId" v-model="filme.id">
					<div :class="{'form-group': true, 'has-error': errors.has('tituloOriginal') }">
						<label class="control-label" for="tituloOriginal">Título Original *</label>
						<input type="text" v-validate="'required'" name='tituloOriginal' id="tituloOriginal" v-model="filme.tituloOriginal" class="form-control">
						<span v-show="errors.has('tituloOriginal')" class="help-block help-block form-error">{{ errors.first('tituloOriginal') }}</span>
					</div>
					<div class="form-group">
						<label class="control-label" for="poster">Poster </label>
						<span class="upload-poster-container"> </span>
						<input type="text" id="poster" placeholder="" v-model="filme.poster" class="form-control " maxlength="255" style="display: none">
					</div>
					<div class="form-group">
						<label class="control-label" for="duracao">Duração </label>
						<input type="text" id="duracao" placeholder="" v-mask="'integer'" v-model="filme.duracao" class="form-control  " maxlength="255">
					</div>
					<div class="form-group">
						<label class="control-label" for="dataLancamento">Data do Lançamento *</label>
						<div class="input-group">
							<date-picker v-mask="'datetime'" v-model="filme.dataLancamento" :config="{format: 'DD/MM/YYYY HH:mm',useCurrent: false}"></date-picker>
							<div class="input-group-addon	append-right">
								<span class="fa fa-calendar"></span>
							</div>
						</div>
					</div>
					<div class="form-group">
						<label class="control-label" for="sinopse">Sinopse *</label>
						<textarea rows="3" placeholder="Sinopse" data-validation="required" v-model="filme.sinopse" class="form-control " maxlength="2000">Sinopse</textarea>
					</div>
					<div class="form-group   ">
						<label class="control-label" for="titulo">Título </label>
						<input type="text" id="titulo" placeholder="" v-model="filme.titulo" class="form-control  " maxlength="255">
					</div>
					<div class="form-group">
						<label class="control-label" for="diretor">Diretor </label>
						<input type="text" id="diretor" placeholder="" v-model="filme.diretor" class="form-control  " maxlength="255">
					</div>
					<div class="panel">
						<div class="panel-heading">
							<h3 class="panel-title">Elenco</h3>
						</div>
						<div class="">
							<div class="multiselect-elenco-container"></div>
						</div>
					</div>
					<div class="form-group   ">
						<p class="control-label" for="diretor">Trazer pão</p>
						<toggle-button :value="false" :width="70" :height="30" :color="{checked: '#0000FF', unchecked: '#FF0000'}" :sync="true" :labels="{checked: 'Sim', unchecked: 'Não'}" />
					</div>
				</form>
			</div>
		</div>
		<div>
			<div class="clearfix form-actions">
				<a @click="save" class="btn btn-primary btn-lg ">
					<i class="fa fa-check "></i>
					Salvar
				</a>
				&nbsp;
				<a @click="save(true)" class="btn btn-info btn-lg">
					<i class="fa fa-check "></i>
					Salvar e Continuar
				</a>
				&nbsp;
				<a @click="goBackList" class="btn-lg btn btn-light">
					<i class=" fa fa-undo "></i>
					Voltar para a listagem
				</a>
			</div>
		</div>
	</div>
</div>
</template>
<script>
import HttpRequest from "@/components/core/HttpRequest";

export default {
  name: "FormFilme",

  created() {
    this.service = new HttpRequest("/rs/crud/filmes");
  },

  mounted() {
    let id = this.$route.params.id;
    if (id) {
      this.service.getById(
        id,
        data => {
          this.filme = data;
        },
        error => {
          console.error("Error gettin By Id, " + error);
        }
      );
    }
  },

  data: function() {
    return {
      filme: {}
    };
  },

  methods: {
    save: function(_continue) {
      this.service.save(
        this.filme,
        data => {
          this.filme = data;
        },
        error => {
          console.error("error saving filme ", error);
        }
      );
    },

    goBackList: function() {
      this.$router.push({ path: "/filmes/list" });
    }
  }
};
</script>
