package ${application.corePackage}.persistence.pagination;

import java.util.List;
/* generated by JSetup ${JSetupVersion} :  at ${.now} */
public class Pager<Entity> {
    private final List<Entity> items;
    private final Integer actualPage;
    private final Long totalRecords;

    public Pager() {
        this(null, 0, 10L);
    }
    
    public Pager(List<Entity> items, Integer actualPage, Long totalRecords) {
        super();
        this.items = items;
        this.actualPage = actualPage;
        this.totalRecords = totalRecords;
    }
    public List<Entity> getItems() {
        return items;
    }

    public Integer getActualPage() {
        return actualPage;
    }

    public Long getTotalRecords() {
        return totalRecords;
    }

}
