/* generated by JSetup ${JSetupVersion} :  at ${.now} */
package ${application.corePackage}.persistence.pagination;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;

import java.util.List;

@Getter
@Builder
@AllArgsConstructor
public class Pagination<T> {

	private final Long totalRecords;
	private final List<T> results;
}