package ${application.corePackage}.json;

import java.io.Serializable;

import org.apache.commons.lang3.exception.ExceptionUtils;

/* generated by JSetup ${JSetupVersion} :  at ${.now} */
public class JsonError implements Serializable {
	private static final long serialVersionUID = 1L;
	private String type;
	private String errorMessage;
	private Object parameters;
	private String legalMessage;

	public JsonError(Exception error, String legalMessage) {
		this(ExceptionUtils.getStackTrace(error), legalMessage);
		setType(error.getClass().getSimpleName());
	}

	public JsonError(String errorMessage, String leString) {
		this(errorMessage, null, leString);
	}

	public JsonError(String errorMessage, Object parameters) {
		this(errorMessage, parameters, "");
	}

	public JsonError(Exception e, String errorMessage, Object parameters, String legalMessage) {
		this(ExceptionUtils.getStackTrace(e) + " " + errorMessage, parameters, legalMessage);
	}

	public JsonError(String errorMessage, Object parameters, String legalMessage) {
		setErrorMessage(errorMessage);
		setLegalMessage(legalMessage);
		setParameters(parameters);
	}

	public JsonError() {

	}

	public JsonError(Exception e, String errorMessage, Object parameters) {
		String message = "";
		if (e.getCause() != null) {
			message = ExceptionUtils.getStackTrace(e) + " cause : \n" + ExceptionUtils.getStackTrace(e.getCause());
		} else {
			message = ExceptionUtils.getStackTrace(e);
		}

		setErrorMessage(message);
		setParameters(parameters);
	}

	public String getErrorMessage() {
		return errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public Object getParameters() {
		return parameters;
	}

	public void setParameters(Object parameters) {
		this.parameters = parameters;
	}

	public String getLegalMessage() {
		return legalMessage;
	}

	public void setLegalMessage(String legalMessage) {
		this.legalMessage = legalMessage;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
}