<!-- ${entity.name}´s form generated by JSetup ${JSetupVersion} :  at ${.now}  -->
<template>
<div >
	<div class="panel">
		<div class="panel-heading">
			<h3 class="panel-title">
				<i class="fa fa-search"></i>
				Pesquisa de ${firstUpper(entity.displayName)}.
			</h3>
		</div>
		<div class="panel-body">
			<div id="messages_div"></div>
			<form id="form${firstUpper(entity.name)}Filter">
				<div class="widget-main ">
					<div class="row pad-hor-7">
						<div class="col-xs-6">
							<a @click="create" class="btn btn-info">
								<i class="fa fa-plus-circle"></i>
								Novo Registro
							</a>
							&nbsp;
							<a @click="reset" class="btn btn-default ">Limpar</a>
						</div>
						<div class="col-sm-6">
						<#list entity.basicSearches as basicAttr>
							<div class="input-group">
								<input  type="text" v-model="datatableConfig.filterParameters.${firstUpper(basicAttr.name)}" class=" form-control" placeholder="Pesquisar ${entity.displayName} por ${firstUpper(basicAttr.displayName)}">
								<span id="query" class="input-group-btn ">
									<button type="button"  @click="paginate()" class="btn btn-default" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Pesquisando...">
										<span class="fa fa-search icon-on-right  "></span>
										Pesquisar
									</button>
								</span>
							</div>
						</#list>
						<#if entity.completeSearch>
							<div>
								<a @click="showAdvanceSearch = !showAdvanceSearch" > Pesquisa avançada... </a>
							</div>
						</#if>
						</div>
					</div>
				<collapse v-model="showAdvanceSearch">
					<div class="panel" >
							<div class="panel-heading">
								<h5 class="panel-title">Filtros avançados</h5>
							</div>
							<div class="panel-body">

			<#list entity.attributes as att>
				<#if att.viewApproach?? >
					<#if att.type.className == 'Boolean' && att.viewApproach.type  == 'check'>
							<div class="form-group">
								<p class="control-label" for="${firstLower(att.name)}">${firstUpper(att.displayName)!firstLower(att.name)}  </p>
								<toggle-button  v-model="datatableConfig.filterParameters.${firstLower(att.name)}" :width="70" :height="30" :color="{checked: '#7ABE5C', unchecked: '#8F9EA6'}" :sync="true" :labels="{checked: 'Sim', unchecked: 'Não'}"/>
							</div>					
					<#elseif att.viewApproach.type  == 'datepicker'>	
							<div class="form-group">
								<label class="control-label" for="${firstLower(att.name)}">${firstUpper(att.displayName)!firstLower(att.name)}</label>
								<div class="input-group">
									<date-picker v-mask="'datetime'" v-model="datatableConfig.filterParameters.${firstLower(att.name)}" :config="{format: '${att.dateFormat}',useCurrent: false}"></date-picker>
									<div class="input-group-addon	append-right">
										<span class="fa fa-calendar"></span>
									</div>
								</div>
							</div>
					<#elseif att.viewApproach.type  == 'radiogroup'>
					<#elseif att.viewApproach.type  == 'combo'>
					<#elseif att.viewApproach.type  == 'textarea'>	
							<div class="form-group">
								<label class="control-label" for="${firstLower(att.name)}">${firstUpper(att.displayName)!firstLower(att.name)}>${firstUpper(att.displayName)!firstLower(att.name)}</label>
								<textarea rows="3"  v-model="datatableConfig.filterParameters.${firstLower(att.name)}"  class="form-control" maxlength="2000"></textarea>
							</div>					
					<#elseif att.viewApproach.type  == 'upload'>	
					<#else>	
							<div class="form-group">
								<label class="control-label" for="${firstLower(att.name)}">${firstUpper(att.displayName)!firstUpper(att.name)}</label>
								<input type="text" name='${firstLower(att.name)}'  v-model="datatableConfig.filterParameters.${firstLower(att.name)}" class="form-control" >
							</div>
					</#if>
		  	   <#else>
		  	   </#if>
			</#list> 
			<#if entity.relationships??>	
				<#list entity.relationships as rel>
				</#list> 
		   </#if>
																																			
								<!-- inicio dos registros-->
								<div id="groupInputTituloOriginal" class="form-group   ">
									<label class="control-label" for="inputTituloOriginal">Título</label>
									<input type="text" v-model="datatableConfig.filterParameters.tituloOriginal" placeholder="Pesquise pelo Título" class="form-control">
								</div>
								<div>
									<button type="button" @click="paginate()"  class="btn btn-info btn-sm search-button loading-button" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Pesquisando...">
										<i class="fa fa-search"></i>
										Pesquisar
									</button>
								</div>
							</div>
						</div>
				</collapse>
				</div>
			</form>
			<div class="center">
				<div class="">
					<div class="">
						<i v-if="!datatableConfig.loading" class="fa fa-align-justify"></i>
						<i v-if="datatableConfig.loading" class="fa fa-spinner fa-spin fa-fw"></i>
						Resultado da pesquisa
					</div>
					<table class="table table-striped table-bordered table-hover  no-footer  ">
						<thead>
							<tr>
						<#list entity.attributes as att>
								<th class="th-${firstLower(att.name)}}}">
									<a >
										<i class="fa "></i>
										${firstUpper(att.displayName)!firstLower(att.name)}
									</a>
								</th>
						</#list> 
						<#list entity.relationships as rel >
							<#if rel.showInPages && rel.viewApproach?? && rel.viewApproach.type == 'modal'  || rel.viewApproach.type == 'combo'>
								<th class="th-${firstLower(rel.name)}}}">
									<a >
										<i class="fa "></i>
										${firstUpper(rel.displayName)!firstUpper(rel.name)}
									</a>
								</th>
							</#if>
						</#list>
								<th > Ações </th>
							</tr>
						</thead>
						<tbody>
							<tr v-for="${firstLower(entity.name)} in datatableConfig.items " :key="${firstLower(entity.name)}.id">
						<#list entity.attributes as att>									
								<td>{{${firstLower(entity.name)}.${firstLower(att.name)}}}</td>
						</#list> 
						<#list entity.relationships as rel >
							<#if rel.showInPages && rel.viewApproach?? && rel.viewApproach.type == 'modal'  || rel.viewApproach.type == 'combo'>
								<#if rel.viewApproach.type == 'modal'>
								<td>{{${firstLower(entity.name)}.${rel.name}.${rel.viewApproach.textField} }}</td>
								<#elseif rel.viewApproach.type == 'combo'>
								<td>{{${firstLower(entity.name)}.${rel.name}.${rel.viewApproach.comboVal} }}</td>										
								</#if>
							</#if>
						</#list>
								<td class="td-actions action-butons-cell">
									<a href="javascript:void(-1)" class="btn btn-xs  btn-primary " @click="edit${firstUpper(entity.name)}(${firstLower(entity.name)})" data-toggle="tooltip" data-placement="top" title="" data-original-title="Editar ${firstUpper(entity.displayName)}">
										<i class="fa fa-pencil fa-lg"></i>
									</a>
									<a href="javascript:void(-1)" class="btn btn-xs btn-danger " @click="remove${firstUpper(entity.name)}(${firstLower(entity.name)})" data-toggle="tooltip" data-placement="top" title="" data-original-title="Remover ${firstUpper(entity.name)}">
										<i class="fa fa-trash fa-lg"></i>
									</a>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="">
					<div class="col-md-6" style="text-align: left; margin: 15px 0">
						<div class=" float-left ">
							<span v-if="datatableConfig.loading" class="loading-elements">
								<span class="">
									<i v-if="datatableConfig.loading" class="fa fa-spinner fa-spin fa-fw"></i>
									Carregando...
								</span>
							</span>
							<span v-if="!datatableConfig.loading" class="has-elements" style="display: inline;">
								Registros
								<span class="initial-page">{{datatableConfig.first}}</span>
								a
								<span class="final-page">{{datatableConfig.last}}</span>
								de
								<span class="total-records">{{datatableConfig.totalRecords}}</span>
								. Exibindo até
								<select class="combo-page-size" v-on:change="paginate()" v-model="datatableConfig.pageSize"  style="padding: 0 0 0 0; height: 20px">
									<option value="3">3</option>
									<option value="5">5</option>
									<option value="10" >10</option>
									<option value="25">25</option>
									<option value="50">50</option>
								</select>
								por página.
							</span>
						</div>
					</div>
					<div class="">
					    <pagination v-model="datatableConfig.page" v-on:change="paginate" :total-page="datatableConfig.totalPages" align="right" />
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

</template>
<script>
import DatatableConfig from "@/components/core/DatatableConfig";
import HttpRequest from "@/components/core/HttpRequest";

export default {
  created: function() {
    this.service = new HttpRequest("/rs/crud/${firstLower(entity.name)}s");
  },

  mounted: function() {
    this.paginate();
  },

  data: function() {
    return {
      showAdvanceSearch: false,
      datatableConfig: new DatatableConfig()
    };
  },

  methods: {
    create: function() {
      this.$router.push({ path: "/${firstLower(entity.name)}s/new/" });
    },

    edit${firstUpper(entity.name)}: function(_${firstLower(entity.name)}) {
      this.$router.push({ path: "/${firstLower(entity.name)}s/edit/" + _${firstLower(entity.name)}.id });
    },

    reset: function() {
      this.datatableConfig = new DatatableConfig();
    },

    remove${firstUpper(entity.name)}: function(_${firstLower(entity.name)}) {
      console.log("remove${firstUpper(entity.name)}" + _${firstLower(entity.name)});
    },

    paginate: function(pageIndex = 1) {
      this.datatableConfig.page = pageIndex;

      this.service.getPage(
        this.datatableConfig,
        data => {
          console.debug("success fetching ${firstLower(entity.name)}´s page", data);
        },

        error => {
          console.error("error fetching ${firstLower(entity.name)}´s page", error);
        }
      );
    }
  }
};
</script> 
