/** Application Router  generated by JSetup ${JSetupVersion} :  at ${.now} **/
import React from 'react';
import { HashRouter as Router, Route, Switch } from 'react-router-dom';

<#list application.entities as entity>
import Form${entity.name} from '../components/${firstLower(entity.name)}/Form${entity.name}.vue'
import Page${entity.name} from '../components/${firstLower(entity.name)}/Page${entity.name}.vue'
</#list>

const Root = () => {
  return (
    <Router>
      <div>
		<#list application.entities as entity>  
         <Route path="/${firstLower(entity.name)}s/edit/:id" component={Form${entity.name}} exact />
         <Route path="/${firstLower(entity.name)}s/new" component={Form${entity.name}} exact />
         <Route path="/${firstLower(entity.name)}s/list" component={Page${entity.name}} exact />
		</#list>
      </div>
    </Router>
  );
};

export default Root;

