/* ${entity.name}´s Search Page generated by JSetup ${JSetupVersion} :  at ${.now}  */
import React from "react";
import Form${firstUpper(entity.name)} from "@/page-sessions/${firstLower(entity.name)}/Form${firstUpper(entity.name)}";

function Create${firstUpper(entity.name)}() {
  return <Form${firstUpper(entity.name)} />
}

export default Create${firstUpper(entity.name)}

