/* ${entity.name}´s List Page generated by JSetup ${JSetupVersion} :  at ${.now}  */
import React from "react";
import List${firstUpper(entity.name)} from "@/page-sessions/${firstLower(entity.name)}/List${firstUpper(entity.name)}";

function ListPage() {
  return <List${firstUpper(entity.name)} />;
}

export default ListPage;
