package ${application.corePackage}.security;

import java.util.Collection;


import javax.inject.Inject;
import javax.inject.Named;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.annotation.Propagation;

import ${application.rootPackage}.model.User;
import ${application.rootPackage}.persistence.DaoUser;

/**
*  generated by JSetup ${JSetupVersion} :  at ${.now}
**/
@Named
@Transactional(readOnly = true, propagation = Propagation.REQUIRES_NEW)
public class UserDetailsServiceImp implements UserDetailsService {
	private final DaoUser userDao;


	@Inject
	SpringSecurityUserContext context;

	@Inject
	public UserDetailsServiceImp(DaoUser userDao) {
		if (userDao == null) {
			throw new IllegalArgumentException("UserDao cannot be null");
		}
		this.userDao = userDao;
	}

	@Override
	public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
		<#if application.multitenancy>
		User appUser = userDao.findByUsername(username, context.getOwner());
		<#else>
		User appUser = userDao.findByUsername(username);
		</#if>
		if (appUser == null) {
			throw new UsernameNotFoundException("Invalid username...");
		}
		return appUser;
	}
}