// carousel data
export const mainCarouselData = [
  {
    title: "Fashionable Collection",
    imgUrl: "/assets/images/products/bag.png",
    description: "Get Free Shipping on all orders over $99.00",
    buttonText: "Shop Now",
    buttonLik: "#",
  },
  {
    title: "Fashionable Collection",
    imgUrl: "/assets/images/products/nike-black.png",
    description: "Get Free Shipping on all orders over $99.00",
    buttonText: "Shop Now",
    buttonLik: "#",
  },
];

// categories
export const categories = [
  {
    id: "96c813a8-efff-4a51-8926-fc674757a135",
    name: "Men's Fashion",
    icon: null,
    image: "/assets/images/products/t-shirt4.png",
    slug: "men's-fashion",
    parent: [],
    description: null,
    for: {
      demo: "fashion-2",
      type: "top-categories",
    },
  },
  {
    id: "76f4a1dd-fd27-461e-8b59-bfc3c1da6895",
    name: "Women's Fashion",
    icon: null,
    image: "/assets/images/products/t-shirt5.png",
    slug: "women's-fashion",
    parent: [],
    description: null,
    for: {
      demo: "fashion-2",
      type: "top-categories",
    },
  },
  {
    id: "e6d2c2e3-d973-4367-98d8-0c140fbaf390",
    name: "Gadgets",
    icon: null,
    image: "/assets/images/products/smartwatch-2.png",
    slug: "gadgets",
    parent: [],
    description: null,
    for: {
      demo: "fashion-2",
      type: "top-categories",
    },
  },
  {
    id: "f7b1da64-4d03-4a10-b364-67a2589b9de1",
    name: "Cosmatics",
    icon: null,
    image: "/assets/images/products/casmatics.jpg",
    slug: "cosmatics",
    parent: [],
    description: null,
    for: {
      demo: "fashion-2",
      type: "top-categories",
    },
  },
];

// services
export const serviceList = [
  {
    id: "5777f551-aca2-4b94-8e55-f170fbb52d25",
    icon: "Truck",
    title: "Fast Delivery",
    description: "Start from $10",
  },
  {
    id: "7ba08a7d-9f00-43be-a632-7d2123f95109",
    icon: "MoneyGuarantee",
    title: "Money Guarantee",
    description: "7 Days Back",
  },
  {
    id: "5a50c887-3bea-488f-be1c-0ecc216780fd",
    icon: "AlarmClock",
    title: "365 Days",
    description: "For free return",
  },
  {
    id: "f2ad1b40-0aeb-4fb0-af34-1f2b475f89ed",
    icon: "Payment",
    title: "Payment",
    description: "Secure system",
  },
];

// brands
export const brandList = [
  {
    id: "9aee1898-23e0-4965-8f0d-427dc963ae07",
    slug: "alibaba",
    name: "AliBaba",
    image: "/assets/images/brands/alibaba.png",
    type: "fashion",
  },
  {
    id: "024ec2a2-7ca7-46c2-8990-f78ac4215dd1",
    slug: "levis",
    name: "Levis",
    image: "/assets/images/brands/levis.png",
    type: "fashion",
  },
  {
    id: "e370f16a-90e2-4f26-b9af-a38d6f645a4c",
    slug: "lotto",
    name: "Lotto",
    image: "/assets/images/brands/lotto.png",
    type: "fashion",
  },
  {
    id: "d8f4c60e-6bac-4fdc-9880-999fbddac97d",
    slug: "raymond",
    name: "Raymond",
    image: "/assets/images/brands/raymond.png",
    type: "fashion",
  },
  {
    id: "0c74cb7c-6082-4640-9380-815928be7127",
    slug: "samsung",
    name: "Samsung",
    image: "/assets/images/brands/samsung.png",
    type: "fashion",
  },
];

// products
export const products = [
  {
    id: "d6a6333d-9ab1-45a1-9004-0cde081df41b",
    slug: "silver-high-neck-sweater",
    shop: {
      id: "01c8fedf-4d40-43d2-b62e-c4134d870036",
      slug: "scarlett-beauty",
      user: {
        id: "4af8dc65-c32f-4ae5-b95c-83e6ff2de216",
        email: "Jamey58@yahoo.com",
        phone: "(232) 669-5103 x109",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/358.jpg",
        password: "glSxS6fU4TsjMde",
        dateOfBirth: "1962-09-18T09:47:00.288Z",
        verified: true,
        name: {
          firstName: "Grover",
          lastName: "Haley",
        },
      },
      email: "Fatima12@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Silver High Neck Sweater",
    brand: null,
    price: 210,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/1.SilverHighNeckSweater.png",
    images: [
      "/assets/images/products/Fashion/Clothes/1.SilverHighNeckSweater.png",
      "/assets/images/products/Fashion/Clothes/1.SilverHighNeckSweater.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "best-selling-product",
    },
  },
  {
    id: "6c613a19-e53d-434f-824d-8d06912d956c",
    slug: "yellow-casual-sweater",
    shop: {
      id: "3a05f65b-862d-407b-8c57-ffd556c22dc2",
      slug: "word-wide-wishes",
      user: {
        id: "14b0a7cb-1dd4-41d6-aeac-fbd20d84fc5a",
        email: "Roy.Wehner45@gmail.com",
        phone: "751.642.8828 x9943",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1123.jpg",
        password: "e_N9bM67AMX0a9N",
        dateOfBirth: "1974-08-24T18:42:00.569Z",
        verified: true,
        name: {
          firstName: "Sean",
          lastName: "Purdy",
        },
      },
      email: "Maritza_Bednar33@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Yellow Casual Sweater",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/21.YellowCasualSweater.png",
    images: [
      "/assets/images/products/Fashion/Clothes/21.YellowCasualSweater.png",
      "/assets/images/products/Fashion/Clothes/21.YellowCasualSweater.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "best-selling-product",
    },
  },
  {
    id: "5452751b-4fb2-42fb-a805-fbd3663bb718",
    slug: "denim-blue-jeans",
    shop: {
      id: "60a222a4-47d4-4073-814c-b61c19ac554e",
      slug: "coveted-clicks",
      user: {
        id: "4665f68b-885c-40a6-a652-89f01a2e1880",
        email: "Kip_Stanton@hotmail.com",
        phone: "(636) 895-6094 x1153",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/534.jpg",
        password: "ubupvNnXXaiMxr6",
        dateOfBirth: "1976-02-06T02:59:20.087Z",
        verified: true,
        name: {
          firstName: "Terrance",
          lastName: "Wiza",
        },
      },
      email: "Adella.Murphy@yahoo.com",
      name: "Coveted Clicks",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-3.png",
      profilePicture: "/assets/images/faces/propic(2).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Denim Blue Jeans",
    brand: null,
    price: 140,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/Fashion/Clothes/4.DenimBlueJeans.png",
    images: [
      "/assets/images/products/Fashion/Clothes/4.DenimBlueJeans.png",
      "/assets/images/products/Fashion/Clothes/4.DenimBlueJeans.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "best-selling-product",
    },
  },
  {
    id: "25f36ec4-c1f4-407a-a7f3-d80bef802b1c",
    slug: "black-white-sweater",
    shop: {
      id: "ab3e2f79-47a1-450b-af90-67760bd32941",
      slug: "anytime-buys",
      user: {
        id: "64308093-b62c-4937-9306-4d315b65f464",
        email: "Candice62@hotmail.com",
        phone: "994-314-2257",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/222.jpg",
        password: "3Qcygz7JA1EOfaC",
        dateOfBirth: "1995-12-27T17:31:02.789Z",
        verified: true,
        name: {
          firstName: "Cale",
          lastName: "Schneider",
        },
      },
      email: "Davonte.Pfeffer@gmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Black White Sweater",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/19.BlackWhiteSweater.png",
    images: [
      "/assets/images/products/Fashion/Clothes/19.BlackWhiteSweater.png",
      "/assets/images/products/Fashion/Clothes/19.BlackWhiteSweater.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "best-selling-product",
    },
  },
  {
    id: "3f46a020-14ab-4c1e-a135-61b24f066a39",
    slug: "gray-overcoat-women",
    shop: {
      id: "3a05f65b-862d-407b-8c57-ffd556c22dc2",
      slug: "word-wide-wishes",
      user: {
        id: "14b0a7cb-1dd4-41d6-aeac-fbd20d84fc5a",
        email: "Roy.Wehner45@gmail.com",
        phone: "751.642.8828 x9943",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1123.jpg",
        password: "e_N9bM67AMX0a9N",
        dateOfBirth: "1974-08-24T18:42:00.569Z",
        verified: true,
        name: {
          firstName: "Sean",
          lastName: "Purdy",
        },
      },
      email: "Maritza_Bednar33@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Gray Overcoat Women",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/20.GrayOvercoatWomen.png",
    images: [
      "/assets/images/products/Fashion/Clothes/20.GrayOvercoatWomen.png",
      "/assets/images/products/Fashion/Clothes/20.GrayOvercoatWomen.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "best-selling-product",
    },
  },
  {
    id: "e3010a87-11e6-403d-a3ed-7ecab62926ce",
    slug: "women's-fashion",
    shop: {
      id: "60a222a4-47d4-4073-814c-b61c19ac554e",
      slug: "coveted-clicks",
      user: {
        id: "4665f68b-885c-40a6-a652-89f01a2e1880",
        email: "Kip_Stanton@hotmail.com",
        phone: "(636) 895-6094 x1153",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/534.jpg",
        password: "ubupvNnXXaiMxr6",
        dateOfBirth: "1976-02-06T02:59:20.087Z",
        verified: true,
        name: {
          firstName: "Terrance",
          lastName: "Wiza",
        },
      },
      email: "Adella.Murphy@yahoo.com",
      name: "Coveted Clicks",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-3.png",
      profilePicture: "/assets/images/faces/propic(2).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Women's Fashion",
    brand: null,
    price: 140,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
    images: [
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
    ],
    categories: ["Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "best-selling-product",
    },
  },
  {
    id: "a178627b-85a8-448a-afd1-eb6b90078a0d",
    slug: "nike-red",
    shop: {
      id: "3a05f65b-862d-407b-8c57-ffd556c22dc2",
      slug: "word-wide-wishes",
      user: {
        id: "14b0a7cb-1dd4-41d6-aeac-fbd20d84fc5a",
        email: "Roy.Wehner45@gmail.com",
        phone: "751.642.8828 x9943",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1123.jpg",
        password: "e_N9bM67AMX0a9N",
        dateOfBirth: "1974-08-24T18:42:00.569Z",
        verified: true,
        name: {
          firstName: "Sean",
          lastName: "Purdy",
        },
      },
      email: "Maritza_Bednar33@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Red",
    brand: null,
    price: 210,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/Fashion/Shoes/1.Nike Red.png",
    images: [
      "/assets/images/products/Fashion/Shoes/1.Nike Red.png",
      "/assets/images/products/Fashion/Shoes/1.Nike Red.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "best-selling-product",
    },
  },
  {
    id: "f88c128c-27e7-4479-95f1-b18e28528ff8",
    slug: "north-star-blue",
    shop: {
      id: "b62bebd8-c1ad-4602-b8ca-130e793b1fa0",
      slug: "constant-shoppers",
      user: {
        id: "e0f8f622-ce15-41d9-a961-237b2e2a44a0",
        email: "Armani.Haag77@yahoo.com",
        phone: "1-864-519-7024 x18622",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1076.jpg",
        password: "_g0E0cCK1jvA3Oe",
        dateOfBirth: "1997-01-28T02:57:51.397Z",
        verified: true,
        name: {
          firstName: "Armand",
          lastName: "Paucek",
        },
      },
      email: "Tyra.Kilback60@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "North Star Blue",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/Fashion/Shoes/21.NorthStarBlue.png",
    images: [
      "/assets/images/products/Fashion/Shoes/21.NorthStarBlue.png",
      "/assets/images/products/Fashion/Shoes/21.NorthStarBlue.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "best-selling-product",
    },
  },
  //   feature products
  {
    id: "5e82e187-c3bd-4589-ae13-e3e9d0d3bacb",
    slug: "denim-classic-blue-jeans",
    shop: {
      id: "12e519bc-ad1d-465f-8307-90e2ee5d68b1",
      slug: "word-wide-wishes",
      user: {
        id: "c203bf6b-fa49-462b-9e81-bb544538e2c0",
        email: "Emmanuel.Wilkinson@yahoo.com",
        phone: "224.760.0494",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1.jpg",
        password: "muuWPwPsN8lSo_m",
        dateOfBirth: "1980-07-04T12:04:06.468Z",
        verified: true,
        name: {
          firstName: "Maximilian",
          lastName: "Terry",
        },
      },
      email: "Evangeline.Toy69@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Denim Classic Blue Jeans",
    brand: null,
    price: 310,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/7.DenimClassicBlueJeans.png",
    images: [
      "/assets/images/products/Fashion/Clothes/7.DenimClassicBlueJeans.png",
      "/assets/images/products/Fashion/Clothes/7.DenimClassicBlueJeans.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "featured-products",
    },
  },
  {
    id: "7ca294fc-be16-4d2a-8441-4b1c60624bda",
    slug: "double-wool-overcoat",
    shop: {
      id: "39205790-268b-4c94-9bcc-d7acdce4e016",
      slug: "anytime-buys",
      user: {
        id: "c203bf6b-fa49-462b-9e81-bb544538e2c0",
        email: "Emmanuel.Wilkinson@yahoo.com",
        phone: "224.760.0494",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1.jpg",
        password: "muuWPwPsN8lSo_m",
        dateOfBirth: "1980-07-04T12:04:06.468Z",
        verified: true,
        name: {
          firstName: "Maximilian",
          lastName: "Terry",
        },
      },
      email: "Verna_Schiller@yahoo.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Double Wool Overcoat",
    brand: null,
    price: 310,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/16.DoubleWoolOvercoat.png",
    images: [
      "/assets/images/products/Fashion/Clothes/16.DoubleWoolOvercoat.png",
      "/assets/images/products/Fashion/Clothes/16.DoubleWoolOvercoat.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "featured-products",
    },
  },
  {
    id: "0fa9e8d4-2045-44d6-b0d0-cd4a79cd2afd",
    slug: "royal-black-suit-pant",
    shop: {
      id: "6d42cbe2-f293-464b-96ee-b97a43530aff",
      slug: "keyboard-kiosk",
      user: {
        id: "fdb4c202-a46a-49f6-b8e0-e5cfd5be1ea1",
        email: "Laron48@hotmail.com",
        phone: "(215) 892-6113 x97330",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/88.jpg",
        password: "rmwl_8mmxHsFY3B",
        dateOfBirth: "1972-08-03T22:21:24.223Z",
        verified: true,
        name: {
          firstName: "Felicita",
          lastName: "Heathcote",
        },
      },
      email: "Karianne_Gleason35@hotmail.com",
      name: "Keyboard Kiosk",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-5.png",
      profilePicture: "/assets/images/faces/propic(4).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Royal Black Suit Pant",
    brand: null,
    price: 1140,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/8.RoyalBlackSuitPant.png",
    images: [
      "/assets/images/products/Fashion/Clothes/8.RoyalBlackSuitPant.png",
      "/assets/images/products/Fashion/Clothes/8.RoyalBlackSuitPant.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "featured-products",
    },
  },
  {
    id: "dab58e83-5c28-4707-9a78-79aa42e6a602",
    slug: "blue-trousers",
    shop: {
      id: "12e519bc-ad1d-465f-8307-90e2ee5d68b1",
      slug: "word-wide-wishes",
      user: {
        id: "c203bf6b-fa49-462b-9e81-bb544538e2c0",
        email: "Emmanuel.Wilkinson@yahoo.com",
        phone: "224.760.0494",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1.jpg",
        password: "muuWPwPsN8lSo_m",
        dateOfBirth: "1980-07-04T12:04:06.468Z",
        verified: true,
        name: {
          firstName: "Maximilian",
          lastName: "Terry",
        },
      },
      email: "Evangeline.Toy69@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Blue Trousers",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/Fashion/Clothes/14.BlueTrousers.png",
    images: [
      "/assets/images/products/Fashion/Clothes/14.BlueTrousers.png",
      "/assets/images/products/Fashion/Clothes/14.BlueTrousers.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "featured-products",
    },
  },
  {
    id: "17113fef-e238-4997-910d-68f6efe92772",
    slug: "women's-fashion",
    shop: {
      id: "c988e06d-fe79-4224-94c8-3e8926affa52",
      slug: "coveted-clicks",
      user: {
        id: "562ff1e0-e46a-4a31-9f6d-9b32e8b310ea",
        email: "Laverne_Torp@hotmail.com",
        phone: "(350) 603-8176 x7709",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/882.jpg",
        password: "glgHqyEgs9Ed5EV",
        dateOfBirth: "1976-07-08T12:14:31.674Z",
        verified: true,
        name: {
          firstName: "Clara",
          lastName: "Stark",
        },
      },
      email: "Vivianne.Harber@hotmail.com",
      name: "Coveted Clicks",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-3.png",
      profilePicture: "/assets/images/faces/propic(2).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Women's Fashion",
    brand: null,
    price: 140,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
    images: [
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
    ],
    categories: ["Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "featured-products",
    },
  },
  {
    id: "0c47b3df-37a9-45ca-9aed-af8e2eaebd86",
    slug: "gray-overcoat-women",
    shop: {
      id: "12e519bc-ad1d-465f-8307-90e2ee5d68b1",
      slug: "word-wide-wishes",
      user: {
        id: "c203bf6b-fa49-462b-9e81-bb544538e2c0",
        email: "Emmanuel.Wilkinson@yahoo.com",
        phone: "224.760.0494",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1.jpg",
        password: "muuWPwPsN8lSo_m",
        dateOfBirth: "1980-07-04T12:04:06.468Z",
        verified: true,
        name: {
          firstName: "Maximilian",
          lastName: "Terry",
        },
      },
      email: "Evangeline.Toy69@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Gray Overcoat Women",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/20.GrayOvercoatWomen.png",
    images: [
      "/assets/images/products/Fashion/Clothes/20.GrayOvercoatWomen.png",
      "/assets/images/products/Fashion/Clothes/20.GrayOvercoatWomen.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "featured-products",
    },
  },
  {
    id: "1aad10db-29b9-488b-b1c9-3bf97f29f72a",
    slug: "women's-fashion",
    shop: {
      id: "12e519bc-ad1d-465f-8307-90e2ee5d68b1",
      slug: "word-wide-wishes",
      user: {
        id: "c203bf6b-fa49-462b-9e81-bb544538e2c0",
        email: "Emmanuel.Wilkinson@yahoo.com",
        phone: "224.760.0494",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1.jpg",
        password: "muuWPwPsN8lSo_m",
        dateOfBirth: "1980-07-04T12:04:06.468Z",
        verified: true,
        name: {
          firstName: "Maximilian",
          lastName: "Terry",
        },
      },
      email: "Evangeline.Toy69@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Women's Fashion",
    brand: null,
    price: 140,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
    images: [
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
    ],
    categories: ["Fashion"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-2",
      type: "featured-products",
    },
  },
  //   sale products
  {
    id: "b2c22e0a-7ef9-4412-8848-6c51c718ca11",
    slug: "denim-classic-blue-jeans",
    shop: {
      id: "65528b9d-c3f2-439f-8390-62afe999c6b4",
      slug: "coveted-clicks",
      user: {
        id: "0e9a3e1a-e3fa-4a30-af14-78e1fad92820",
        email: "Letha_OConnell@gmail.com",
        phone: "1-423-630-3490 x324",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/106.jpg",
        password: "i8gZ_Qdk5Pz9yzC",
        dateOfBirth: "1976-12-20T08:22:22.670Z",
        verified: true,
        name: {
          firstName: "Jackson",
          lastName: "Corwin",
        },
      },
      email: "Geovanny84@gmail.com",
      name: "Coveted Clicks",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-3.png",
      profilePicture: "/assets/images/faces/propic(2).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Denim Classic Blue Jeans",
    brand: null,
    price: 310,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/7.DenimClassicBlueJeans.png",
    images: [
      "/assets/images/products/Fashion/Clothes/7.DenimClassicBlueJeans.png",
      "/assets/images/products/Fashion/Clothes/7.DenimClassicBlueJeans.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    rating: 1,
    for: {
      demo: "fashion-2",
      type: "sale-products",
    },
  },
  {
    id: "b1122c1c-0223-424f-acbc-59d5d055ee06",
    slug: "double-wool-overcoat",
    shop: {
      id: "20c72778-d678-440b-b065-d98c37daeaa6",
      slug: "anytime-buys",
      user: {
        id: "f84b0699-d98e-42e1-b3a4-29b90cc8d434",
        email: "Russ_Gulgowski@gmail.com",
        phone: "293-327-5110",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1199.jpg",
        password: "ORwcWcaLD5PUyR1",
        dateOfBirth: "1951-05-19T04:04:19.217Z",
        verified: true,
        name: {
          firstName: "Alice",
          lastName: "Pagac",
        },
      },
      email: "Tania23@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Double Wool Overcoat",
    brand: null,
    price: 310,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/16.DoubleWoolOvercoat.png",
    images: [
      "/assets/images/products/Fashion/Clothes/16.DoubleWoolOvercoat.png",
      "/assets/images/products/Fashion/Clothes/16.DoubleWoolOvercoat.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    rating: 2,
    for: {
      demo: "fashion-2",
      type: "sale-products",
    },
  },
  {
    id: "3b752f4d-d22d-47c5-becd-edcfa4234f05",
    slug: "royal-black-suit-pant",
    shop: {
      id: "e8ffca9d-61f5-4b43-9105-b82531c02c95",
      slug: "scroll-through",
      user: {
        id: "a3ddcb74-02e3-4de9-8909-12d49dc81992",
        email: "Talia.Douglas15@hotmail.com",
        phone: "1-586-304-5888 x2839",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1052.jpg",
        password: "frWLujJjUULTOah",
        dateOfBirth: "1966-06-10T10:15:05.483Z",
        verified: true,
        name: {
          firstName: "Stewart",
          lastName: "Zulauf",
        },
      },
      email: "Dulce.Ankunding@yahoo.com",
      name: "Scroll Through",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner.png",
      profilePicture: "/assets/images/faces/propic(1).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Royal Black Suit Pant",
    brand: null,
    price: 1140,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/8.RoyalBlackSuitPant.png",
    images: [
      "/assets/images/products/Fashion/Clothes/8.RoyalBlackSuitPant.png",
      "/assets/images/products/Fashion/Clothes/8.RoyalBlackSuitPant.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    rating: 1,
    for: {
      demo: "fashion-2",
      type: "sale-products",
    },
  },
  //   latest products
  {
    id: "c1134835-864c-4793-b8d8-9be904007143",
    slug: "nike-red",
    shop: {
      id: "a93f1062-f8a4-432f-a050-daee42cb0b17",
      slug: "scarlett-beauty",
      user: {
        id: "fc726950-618b-401f-b0b9-00b2508886a7",
        email: "Austen88@hotmail.com",
        phone: "(310) 318-4703",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/400.jpg",
        password: "CrzTUZdNc2LJyq_",
        dateOfBirth: "1984-08-31T21:54:41.610Z",
        verified: true,
        name: {
          firstName: "Beau",
          lastName: "McClure",
        },
      },
      email: "Amber67@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-9.png",
      profilePicture: "/assets/images/faces/propic(8).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Red",
    brand: null,
    price: 210,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/Fashion/Shoes/1.Nike Red.png",
    images: [
      "/assets/images/products/Fashion/Shoes/1.Nike Red.png",
      "/assets/images/products/Fashion/Shoes/1.Nike Red.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    rating: 12,
    for: {
      demo: "fashion-2",
      type: "latest-products",
    },
  },
  {
    id: "62815490-76ba-4b93-8e3d-b51aa4bdd33a",
    slug: "north-star-blue",
    shop: {
      id: "3ee7f114-c08e-4485-b5a0-997e03a7bb3a",
      slug: "cybershop",
      user: {
        id: "188a24de-8ef7-4f66-919a-738a5a11458e",
        email: "Dimitri.Hansen@yahoo.com",
        phone: "999.360.4562 x4509",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1238.jpg",
        password: "cQpuGzfLmQIuQ0C",
        dateOfBirth: "1965-12-17T14:47:22.093Z",
        verified: true,
        name: {
          firstName: "Kevon",
          lastName: "Buckridge",
        },
      },
      email: "Daryl_Mann@gmail.com",
      name: "Cybershop",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-8.png",
      profilePicture: "/assets/images/faces/propic(7).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "North Star Blue",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/Fashion/Shoes/21.NorthStarBlue.png",
    images: [
      "/assets/images/products/Fashion/Shoes/21.NorthStarBlue.png",
      "/assets/images/products/Fashion/Shoes/21.NorthStarBlue.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    rating: 10,
    for: {
      demo: "fashion-2",
      type: "latest-products",
    },
  },
  {
    id: "4019e490-e053-4ac0-8215-07bce983777b",
    slug: "puma-black",
    shop: {
      id: "be1bb83d-938a-4784-a045-a982fb54c256",
      slug: "anytime-buys",
      user: {
        id: "6137b2ad-1b1f-4e64-a849-255e0f047c28",
        email: "Retha.Rosenbaum@gmail.com",
        phone: "726.400.6182",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1112.jpg",
        password: "D4jEixqw_zz2fqQ",
        dateOfBirth: "1966-03-13T20:31:00.323Z",
        verified: true,
        name: {
          firstName: "Ike",
          lastName: "Gulgowski",
        },
      },
      email: "Jennings.Stracke@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Puma Black",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    images: [
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    rating: 10,
    for: {
      demo: "fashion-2",
      type: "latest-products",
    },
  },
  //   best week products
  {
    id: "c025ba1b-d2cd-4926-87f9-16c008e36ec4",
    slug: "black-metal-ring",
    shop: {
      id: "326f2236-3868-4df3-b360-4bb032fc0338",
      slug: "scarlett-beauty",
      user: {
        id: "ebfce296-86e4-4d5b-bb8b-c025e8ac3877",
        email: "Allen.Erdman32@yahoo.com",
        phone: "406-796-1774 x1476",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/715.jpg",
        password: "_cxqpGsfzjQ7Z2Q",
        dateOfBirth: "2003-05-29T09:06:47.869Z",
        verified: true,
        name: {
          firstName: "Josiane",
          lastName: "Legros",
        },
      },
      email: "Zella82@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-9.png",
      profilePicture: "/assets/images/faces/propic(8).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Black Metal Ring",
    brand: null,
    price: 140,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Jewellery/2.Black Metal Ring.png",
    images: [
      "/assets/images/products/Fashion/Jewellery/2.Black Metal Ring.png",
      "/assets/images/products/Fashion/Jewellery/2.Black Metal Ring.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    rating: 13,
    for: {
      demo: "fashion-2",
      type: "best-week-products",
    },
  },
  {
    id: "60509025-f0b7-4b13-934d-7b39dab7197e",
    slug: "heavy-stone-colorful-necklace",
    shop: {
      id: "6555efef-5e76-4eb0-a971-ebc3b1cea956",
      slug: "scroll-through",
      user: {
        id: "75703497-9f67-4552-8be3-c2309f206567",
        email: "Savanah.Boyer@hotmail.com",
        phone: "(941) 217-4706",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/160.jpg",
        password: "XlxhE_lkcfqNSfi",
        dateOfBirth: "1960-07-18T17:06:59.803Z",
        verified: true,
        name: {
          firstName: "Oren",
          lastName: "Vandervort",
        },
      },
      email: "Jeanie.Shields95@yahoo.com",
      name: "Scroll Through",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner.png",
      profilePicture: "/assets/images/faces/propic(1).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Heavy Stone Colorful Necklace",
    brand: null,
    price: 1140,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Jewellery/17.HeavyStoneColorfulNecklace.png",
    images: [
      "/assets/images/products/Fashion/Jewellery/17.HeavyStoneColorfulNecklace.png",
      "/assets/images/products/Fashion/Jewellery/17.HeavyStoneColorfulNecklace.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    rating: 1,
    for: {
      demo: "fashion-2",
      type: "best-week-products",
    },
  },
  {
    id: "ca5b9305-b82f-4aae-8dd5-21569e4f84fb",
    slug: "indian-copper-earrings",
    shop: {
      id: "f3e652b1-f3cc-4d33-867d-ad0e6ea0b427",
      slug: "word-wide-wishes",
      user: {
        id: "523a1b04-0a97-4ff0-ac80-1ab7990420ae",
        email: "Sierra42@hotmail.com",
        phone: "663-333-5185 x5005",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/866.jpg",
        password: "Ce8bFPOTVfDrpLD",
        dateOfBirth: "1954-08-13T18:42:21.923Z",
        verified: true,
        name: {
          firstName: "Ellen",
          lastName: "Rosenbaum",
        },
      },
      email: "Terrill54@yahoo.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Indian Copper Earrings",
    brand: null,
    price: 310,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Jewellery/6.IndianCopperEarrings.png",
    images: [
      "/assets/images/products/Fashion/Jewellery/6.IndianCopperEarrings.png",
      "/assets/images/products/Fashion/Jewellery/6.IndianCopperEarrings.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    rating: 2,
    for: {
      demo: "fashion-2",
      type: "best-week-products",
    },
  },
  //   popular products
  {
    id: "b1b8b86d-335f-4d0c-b288-4603215818ed",
    slug: "gray-overcoat-women",
    shop: {
      id: "9f925dc5-0f11-4aa4-925a-4143d4e6c822",
      slug: "keyboard-kiosk",
      user: {
        id: "420b0e2f-d073-4faa-a462-b7b4e36d7439",
        email: "Alfred.Turcotte1@hotmail.com",
        phone: "1-496-499-8882 x6611",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/608.jpg",
        password: "HaTqeYq6hsx2_RY",
        dateOfBirth: "1979-11-23T05:37:58.664Z",
        verified: true,
        name: {
          firstName: "Zander",
          lastName: "Metz",
        },
      },
      email: "Easter.Waters67@yahoo.com",
      name: "Keyboard Kiosk",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-5.png",
      profilePicture: "/assets/images/faces/propic(4).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Gray Overcoat Women",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/20.GrayOvercoatWomen.png",
    images: [
      "/assets/images/products/Fashion/Clothes/20.GrayOvercoatWomen.png",
      "/assets/images/products/Fashion/Clothes/20.GrayOvercoatWomen.png",
    ],
    categories: ["Women's Fashion"],
    status: null,
    reviews: [],
    rating: 10,
    for: {
      demo: "fashion-2",
      type: "popular-products",
    },
  },
  {
    id: "0638049b-37c1-4ebf-bc27-03355ded9123",
    slug: "women's-fashion",
    shop: {
      id: "ec7d6ae0-db1f-48d4-81eb-16d551ce4761",
      slug: "cybershop",
      user: {
        id: "8d7633dc-78e0-468c-a979-77fe2bf83cdc",
        email: "Chad_Hilpert@hotmail.com",
        phone: "1-691-438-5719 x479",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/479.jpg",
        password: "6HwNGIKabt0be_D",
        dateOfBirth: "1970-05-19T02:04:20.504Z",
        verified: true,
        name: {
          firstName: "Dolly",
          lastName: "Moen",
        },
      },
      email: "Eloise63@hotmail.com",
      name: "Cybershop",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-8.png",
      profilePicture: "/assets/images/faces/propic(7).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Women's Fashion",
    brand: null,
    price: 140,
    size: null,
    colors: [],
    discount: 0,
    thumbnail:
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
    images: [
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
      "/assets/images/products/Fashion/Clothes/24.OliveCasualSweater.png",
    ],
    categories: ["Fashion"],
    status: null,
    reviews: [],
    rating: 13,
    for: {
      demo: "fashion-2",
      type: "popular-products",
    },
  },
  {
    id: "8a1a2a07-a04c-40ee-ad19-1913806c6859",
    slug: "blue-trousers",
    shop: {
      id: "9f925dc5-0f11-4aa4-925a-4143d4e6c822",
      slug: "keyboard-kiosk",
      user: {
        id: "420b0e2f-d073-4faa-a462-b7b4e36d7439",
        email: "Alfred.Turcotte1@hotmail.com",
        phone: "1-496-499-8882 x6611",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/608.jpg",
        password: "HaTqeYq6hsx2_RY",
        dateOfBirth: "1979-11-23T05:37:58.664Z",
        verified: true,
        name: {
          firstName: "Zander",
          lastName: "Metz",
        },
      },
      email: "Easter.Waters67@yahoo.com",
      name: "Keyboard Kiosk",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-5.png",
      profilePicture: "/assets/images/faces/propic(4).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Blue Trousers",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/Fashion/Clothes/14.BlueTrousers.png",
    images: [
      "/assets/images/products/Fashion/Clothes/14.BlueTrousers.png",
      "/assets/images/products/Fashion/Clothes/14.BlueTrousers.png",
    ],
    categories: ["Men's Fashion"],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-2",
      type: "popular-products",
    },
  },
];

// articles
export const articles = [
  {
    id: "20a83049-bc4b-41cc-9a29-0b2b69a7fd08",
    title: "30% Off Coupon for Black Friday",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit.…",
    thumbnail: "/assets/images/blogs/blog-1.jpg",
    shop: {
      id: "e7c5030b-0504-4b4c-81dc-1627302bc1a4",
      slug: "scarlett-beauty",
      user: {
        id: "642f50d7-944b-459e-aa20-154afdccb413",
        email: "Annette_Gleason@yahoo.com",
        phone: "(607) 973-2857 x445",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/435.jpg",
        password: "C_mhvNPAeAU7Mj4",
        dateOfBirth: "1963-06-10T22:22:55.842Z",
        verified: true,
        name: {
          firstName: "Rosa",
          lastName: "Pagac",
        },
      },
      email: "Isabella.Kris13@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    user: {
      id: "642f50d7-944b-459e-aa20-154afdccb413",
      email: "Annette_Gleason@yahoo.com",
      phone: "(607) 973-2857 x445",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/435.jpg",
      password: "C_mhvNPAeAU7Mj4",
      dateOfBirth: "1963-06-10T22:22:55.842Z",
      verified: true,
      name: {
        firstName: "Rosa",
        lastName: "Pagac",
      },
    },
    createdAt: "21 SEP",
    slug: "30percent-off-coupon-for-black-friday",
  },
  {
    id: "108015ad-897b-4c90-a90f-53b288ad162c",
    title: "10% Discount for Cosmatics",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit.…",
    thumbnail: "/assets/images/blogs/blog-2.jpg",
    shop: {
      id: "d32b469e-4ccc-43b4-8427-98eba478355f",
      slug: "scroll-through",
      user: {
        id: "992c82b5-8a64-47a3-b665-2b59b6f950e6",
        email: "Enid99@yahoo.com",
        phone: "(672) 865-8949",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/759.jpg",
        password: "ZlNtd6J9UV37Enm",
        dateOfBirth: "1951-03-01T08:56:59.687Z",
        verified: true,
        name: {
          firstName: "Oren",
          lastName: "Pagac",
        },
      },
      email: "Cheyanne.Kutch56@gmail.com",
      name: "Scroll Through",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner.png",
      profilePicture: "/assets/images/faces/propic(1).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    user: {
      id: "bd8b4e8b-6794-42f3-a42f-a2abd903ced9",
      email: "Alexa.Dickens65@yahoo.com",
      phone: "1-904-617-0268 x6023",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/965.jpg",
      password: "PxqJTybdKi_Qrcb",
      dateOfBirth: "1959-12-13T23:47:11.023Z",
      verified: true,
      name: {
        firstName: "Jamar",
        lastName: "Kuhn",
      },
    },
    createdAt: "21 SEP",
    slug: "10percent-discount-for-cosmatics",
  },
  {
    id: "f3f920ba-3f3e-47cd-a109-9183a15479fa",
    title: " Buy 2 get 1 free Offer",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit.…",
    thumbnail: "/assets/images/blogs/blog-3.jpg",
    shop: {
      id: "e7c5030b-0504-4b4c-81dc-1627302bc1a4",
      slug: "scarlett-beauty",
      user: {
        id: "642f50d7-944b-459e-aa20-154afdccb413",
        email: "Annette_Gleason@yahoo.com",
        phone: "(607) 973-2857 x445",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/435.jpg",
        password: "C_mhvNPAeAU7Mj4",
        dateOfBirth: "1963-06-10T22:22:55.842Z",
        verified: true,
        name: {
          firstName: "Rosa",
          lastName: "Pagac",
        },
      },
      email: "Isabella.Kris13@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    user: {
      id: "642f50d7-944b-459e-aa20-154afdccb413",
      email: "Annette_Gleason@yahoo.com",
      phone: "(607) 973-2857 x445",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/435.jpg",
      password: "C_mhvNPAeAU7Mj4",
      dateOfBirth: "1963-06-10T22:22:55.842Z",
      verified: true,
      name: {
        firstName: "Rosa",
        lastName: "Pagac",
      },
    },
    createdAt: "21 SEP",
    slug: "buy-2-get-1-free-offer",
  },
];
