/* ${entity.name}´s Search Page generated by JSetup ${JSetupVersion} :  at ${.now}  */

import Form${firstUpper(entity.name)} from '../../Form${firstUpper(entity.name)}';

export default Form${firstUpper(entity.name)};
