/* ${entity.name}´s Search Page generated by JSetup ${JSetupVersion} :  at ${.now}  */

import Page${firstUpper(entity.name)} from './Page${firstUpper(entity.name)}';

export default Page${firstUpper(entity.name)};
