// carousel-data
export const mainCarouselData = [
  {
    title: "Get groceries delivered within 40 minutes",
    imgUrl: "/assets/images/Groceries Shop/banner-3.png",
    description: null,
    buttonText: "Shop Now",
    buttonLink: "#",
  },
  {
    title: "Get groceries delivered within 40 minutes",
    imgUrl: "/assets/images/Groceries Shop/banner-3.png",
    description: null,
    buttonText: "Shop Now",
    buttonLink: "#",
  },
];

// discount offer list
export const discountOffers = [
  {
    title: "Till 10 Dec, 2021",
    discountOffer: "25% Special Off Today Only for Vegetables",
    imgUrl: "/assets/images/Groceries Shop/vagitable.png",
    buttonText: "Shop Now",
  },
  {
    title: "New Offer!",
    discountOffer: "15% Special Off Today Only for Fruits Item.",
    imgUrl: "/assets/images/Groceries Shop/Offer Card.png",
    buttonText: "Shop Now",
  },
];

// product list
export const products = [
  {
    id: "b66a92a2-56d0-4512-9db6-f24cb97139d4",
    slug: "fresh-line",
    shop: {
      id: "50a7bd5c-8089-416f-b887-9921eebf290e",
      slug: "constant-shoppers",
      user: {
        id: "773532bc-4f41-46d9-94dd-4636c4adb0e4",
        email: "Makayla_Sipes@gmail.com",
        phone: "(329) 360-7080 x9996",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/251.jpg",
        password: "TVkxUX2gm0TXK6u",
        dateOfBirth: "1969-04-01T09:20:22.494Z",
        verified: true,
        name: {
          firstName: "Carter",
          lastName: "Leffler",
        },
      },
      email: "Ian_Monahan@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Fresh Line",
    brand: null,
    price: 146,
    size: null,
    colors: [],
    discount: 7,
    thumbnail: "/assets/images/Groceries Shop/lime.png",
    images: [
      "/assets/images/Groceries Shop/lime.png",
      "/assets/images/Groceries Shop/lime.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 2,
    for: {
      demo: "grocery-3",
      type: "all-products",
    },
  },
  {
    id: "7d65ba4c-2be5-48eb-9378-c51715f74175",
    slug: "mini-papers",
    shop: {
      id: "b416c8df-d589-4628-9d19-7db93c7f8c32",
      slug: "keyboard-kiosk",
      user: {
        id: "71a35f3c-e825-48f8-9ceb-469000897790",
        email: "Jovani_Rice51@yahoo.com",
        phone: "215.250.2065",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/206.jpg",
        password: "_nWJY_eVWSwJr4O",
        dateOfBirth: "1988-09-14T17:39:29.493Z",
        verified: true,
        name: {
          firstName: "Ernestina",
          lastName: "Witting",
        },
      },
      email: "Royal.Waters@yahoo.com",
      name: "Keyboard Kiosk",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-5.png",
      profilePicture: "/assets/images/faces/propic(4).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Mini Papers",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 9,
    thumbnail: "/assets/images/Groceries Shop/MiniPeppers.png",
    images: [
      "/assets/images/Groceries Shop/MiniPeppers.png",
      "/assets/images/Groceries Shop/MiniPeppers.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "grocery-3",
      type: "all-products",
    },
  },
  {
    id: "7e10b5fc-90da-4a78-97f4-05f9a5696cf7",
    slug: "fresh-strawberry",
    shop: {
      id: "791e3523-7489-4217-bcc0-d3377fc1945c",
      slug: "word-wide-wishes",
      user: {
        id: "9df11153-5fd2-4a97-a13f-82a60327517d",
        email: "Alva11@yahoo.com",
        phone: "(712) 354-0462",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/125.jpg",
        password: "YuZI5NTONPqgo4Z",
        dateOfBirth: "1949-05-05T07:40:11.142Z",
        verified: true,
        name: {
          firstName: "Everett",
          lastName: "Murray",
        },
      },
      email: "Erick_Bins@yahoo.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Fresh Strawberry",
    brand: null,
    price: 105,
    size: null,
    colors: [],
    discount: 6,
    thumbnail: "/assets/images/Groceries Shop/strawberry.png",
    images: [
      "/assets/images/Groceries Shop/strawberry.png",
      "/assets/images/Groceries Shop/strawberry.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "grocery-3",
      type: "all-products",
    },
  },
  {
    id: "bf614269-6790-4ff7-999d-cae465a870d6",
    slug: "lemon",
    shop: {
      id: "50a7bd5c-8089-416f-b887-9921eebf290e",
      slug: "constant-shoppers",
      user: {
        id: "773532bc-4f41-46d9-94dd-4636c4adb0e4",
        email: "Makayla_Sipes@gmail.com",
        phone: "(329) 360-7080 x9996",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/251.jpg",
        password: "TVkxUX2gm0TXK6u",
        dateOfBirth: "1969-04-01T09:20:22.494Z",
        verified: true,
        name: {
          firstName: "Carter",
          lastName: "Leffler",
        },
      },
      email: "Ian_Monahan@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Lemon",
    brand: null,
    price: 232,
    size: null,
    colors: [],
    discount: 7,
    thumbnail: "/assets/images/Groceries Shop/Lemon.png",
    images: [
      "/assets/images/Groceries Shop/Lemon.png",
      "/assets/images/Groceries Shop/Lemon.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "grocery-3",
      type: "all-products",
    },
  },
  {
    id: "85192471-bd50-42e8-86ed-14118c95b218",
    slug: "fresh-orange",
    shop: {
      id: "4e6b9915-55a0-4f1c-b31e-65d818422bca",
      slug: "scarlett-beauty",
      user: {
        id: "f38c9fd6-5d6d-480a-b11b-a90f1d84272d",
        email: "Euna.Schumm@hotmail.com",
        phone: "246-881-1059 x3750",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/118.jpg",
        password: "A__wDxc7Qdfoxoh",
        dateOfBirth: "1945-01-23T20:23:11.934Z",
        verified: true,
        name: {
          firstName: "Maxine",
          lastName: "Morissette",
        },
      },
      email: "Vena.Aufderhar@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-9.png",
      profilePicture: "/assets/images/faces/propic(8).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Fresh Orange",
    brand: null,
    price: 164,
    size: null,
    colors: [],
    discount: 11,
    thumbnail: "/assets/images/Groceries Shop/Orange.png",
    images: [
      "/assets/images/Groceries Shop/Orange.png",
      "/assets/images/Groceries Shop/Orange.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "grocery-3",
      type: "all-products",
    },
  },
  {
    id: "9d1833cf-ff97-43fd-8a2e-095fd1dcef72",
    slug: "fresh-line",
    shop: {
      id: "3aa31934-0471-4119-b761-47f4378c491d",
      slug: "cybershop",
      user: {
        id: "b113256d-cb79-4bc4-87a0-38bf65a4ef0c",
        email: "Maxine43@gmail.com",
        phone: "(845) 420-0792",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/731.jpg",
        password: "xZyEeqaC12IAbbd",
        dateOfBirth: "1993-08-07T09:45:53.956Z",
        verified: true,
        name: {
          firstName: "Angelo",
          lastName: "Hahn",
        },
      },
      email: "Sydney67@gmail.com",
      name: "Cybershop",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-8.png",
      profilePicture: "/assets/images/faces/propic(7).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Fresh Line",
    brand: null,
    price: 141,
    size: null,
    colors: [],
    discount: 12,
    thumbnail: "/assets/images/Groceries Shop/lime.png",
    images: [
      "/assets/images/Groceries Shop/lime.png",
      "/assets/images/Groceries Shop/lime.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 2,
    for: {
      demo: "grocery-3",
      type: "all-products",
    },
  },
  {
    id: "33068104-0141-4d19-af79-fd9160fc3e6c",
    slug: "red-apple",
    shop: {
      id: "791e3523-7489-4217-bcc0-d3377fc1945c",
      slug: "word-wide-wishes",
      user: {
        id: "9df11153-5fd2-4a97-a13f-82a60327517d",
        email: "Alva11@yahoo.com",
        phone: "(712) 354-0462",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/125.jpg",
        password: "YuZI5NTONPqgo4Z",
        dateOfBirth: "1949-05-05T07:40:11.142Z",
        verified: true,
        name: {
          firstName: "Everett",
          lastName: "Murray",
        },
      },
      email: "Erick_Bins@yahoo.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Red Apple",
    brand: null,
    price: 145,
    size: null,
    colors: [],
    discount: 7,
    thumbnail: "/assets/images/Groceries Shop/Red apple.png",
    images: [
      "/assets/images/Groceries Shop/Red apple.png",
      "/assets/images/Groceries Shop/Red apple.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 2,
    for: {
      demo: "grocery-3",
      type: "all-products",
    },
  },
  {
    id: "bb51b714-8321-44ea-bc82-6470cab1cb2d",
    slug: "lemon",
    shop: {
      id: "4e6b9915-55a0-4f1c-b31e-65d818422bca",
      slug: "scarlett-beauty",
      user: {
        id: "f38c9fd6-5d6d-480a-b11b-a90f1d84272d",
        email: "Euna.Schumm@hotmail.com",
        phone: "246-881-1059 x3750",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/118.jpg",
        password: "A__wDxc7Qdfoxoh",
        dateOfBirth: "1945-01-23T20:23:11.934Z",
        verified: true,
        name: {
          firstName: "Maxine",
          lastName: "Morissette",
        },
      },
      email: "Vena.Aufderhar@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-9.png",
      profilePicture: "/assets/images/faces/propic(8).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Lemon",
    brand: null,
    price: 216,
    size: null,
    colors: [],
    discount: 9,
    thumbnail: "/assets/images/Groceries Shop/Lemon.png",
    images: [
      "/assets/images/Groceries Shop/Lemon.png",
      "/assets/images/Groceries Shop/Lemon.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "grocery-3",
      type: "all-products",
    },
  },
  {
    id: "0f886319-8b42-4935-967a-4296f743f533",
    slug: "offer-fruits",
    shop: {
      id: "4e6b9915-55a0-4f1c-b31e-65d818422bca",
      slug: "scarlett-beauty",
      user: {
        id: "f38c9fd6-5d6d-480a-b11b-a90f1d84272d",
        email: "Euna.Schumm@hotmail.com",
        phone: "246-881-1059 x3750",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/118.jpg",
        password: "A__wDxc7Qdfoxoh",
        dateOfBirth: "1945-01-23T20:23:11.934Z",
        verified: true,
        name: {
          firstName: "Maxine",
          lastName: "Morissette",
        },
      },
      email: "Vena.Aufderhar@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-9.png",
      profilePicture: "/assets/images/faces/propic(8).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Offer Fruits",
    brand: null,
    price: 198,
    size: null,
    colors: [],
    discount: 12,
    thumbnail: "/assets/images/Groceries Shop/Offer Card.png",
    images: [
      "/assets/images/Groceries Shop/Offer Card.png",
      "/assets/images/Groceries Shop/Offer Card.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "grocery-3",
      type: "all-products",
    },
  },
  {
    id: "b9f9a217-b337-40a1-8342-caa7aca94168",
    slug: "fresh-line",
    shop: {
      id: "043874b1-ddc0-4564-8732-e6ad8e190b20",
      slug: "coveted-clicks",
      user: {
        id: "c8562a7b-1ce7-4b1b-b3ae-da9dfaab9037",
        email: "Milan81@gmail.com",
        phone: "(840) 276-3943",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/143.jpg",
        password: "2xD65G_dkZKpYJz",
        dateOfBirth: "1942-03-07T22:50:35.520Z",
        verified: true,
        name: {
          firstName: "June",
          lastName: "Toy",
        },
      },
      email: "Tracey.Ratke29@hotmail.com",
      name: "Coveted Clicks",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-3.png",
      profilePicture: "/assets/images/faces/propic(2).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Fresh Line",
    brand: null,
    price: 146,
    size: null,
    colors: [],
    discount: 7,
    thumbnail: "/assets/images/Groceries Shop/lime.png",
    images: [
      "/assets/images/Groceries Shop/lime.png",
      "/assets/images/Groceries Shop/lime.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 2,
    for: {
      demo: "grocery-3",
      type: "top-saled-products",
    },
  },
  {
    id: "5d966499-c59b-407c-ae39-1d2a23f364a8",
    slug: "mini-papers",
    shop: {
      id: "77d4d8e7-ff8b-4a9f-ade6-36d0ad289aef",
      slug: "word-wide-wishes",
      user: {
        id: "8f042030-e1fa-4b4e-8c26-dfff2e7c64b3",
        email: "Florence.Wuckert@gmail.com",
        phone: "1-943-951-5017 x601",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1068.jpg",
        password: "cbaWtwTPNJsnGyo",
        dateOfBirth: "1953-06-01T17:12:58.575Z",
        verified: true,
        name: {
          firstName: "Melba",
          lastName: "Hintz",
        },
      },
      email: "Carlie32@gmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Mini Papers",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 9,
    thumbnail: "/assets/images/Groceries Shop/MiniPeppers.png",
    images: [
      "/assets/images/Groceries Shop/MiniPeppers.png",
      "/assets/images/Groceries Shop/MiniPeppers.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "grocery-3",
      type: "top-saled-products",
    },
  },
  {
    id: "9646f53d-7b4b-4c30-990e-eb68f21e39df",
    slug: "fresh-strawberry",
    shop: {
      id: "0630a5fe-717a-49df-94f0-7b919caaa459",
      slug: "scarlett-beauty",
      user: {
        id: "8f042030-e1fa-4b4e-8c26-dfff2e7c64b3",
        email: "Florence.Wuckert@gmail.com",
        phone: "1-943-951-5017 x601",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1068.jpg",
        password: "cbaWtwTPNJsnGyo",
        dateOfBirth: "1953-06-01T17:12:58.575Z",
        verified: true,
        name: {
          firstName: "Melba",
          lastName: "Hintz",
        },
      },
      email: "Nicholaus.Champlin@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Fresh Strawberry",
    brand: null,
    price: 105,
    size: null,
    colors: [],
    discount: 6,
    thumbnail: "/assets/images/Groceries Shop/strawberry.png",
    images: [
      "/assets/images/Groceries Shop/strawberry.png",
      "/assets/images/Groceries Shop/strawberry.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "grocery-3",
      type: "top-saled-products",
    },
  },
  {
    id: "4423952c-caca-4220-a854-dd6c36bf226f",
    slug: "lemon",
    shop: {
      id: "043874b1-ddc0-4564-8732-e6ad8e190b20",
      slug: "coveted-clicks",
      user: {
        id: "c8562a7b-1ce7-4b1b-b3ae-da9dfaab9037",
        email: "Milan81@gmail.com",
        phone: "(840) 276-3943",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/143.jpg",
        password: "2xD65G_dkZKpYJz",
        dateOfBirth: "1942-03-07T22:50:35.520Z",
        verified: true,
        name: {
          firstName: "June",
          lastName: "Toy",
        },
      },
      email: "Tracey.Ratke29@hotmail.com",
      name: "Coveted Clicks",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-3.png",
      profilePicture: "/assets/images/faces/propic(2).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Lemon",
    brand: null,
    price: 232,
    size: null,
    colors: [],
    discount: 7,
    thumbnail: "/assets/images/Groceries Shop/Lemon.png",
    images: [
      "/assets/images/Groceries Shop/Lemon.png",
      "/assets/images/Groceries Shop/Lemon.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "grocery-3",
      type: "top-saled-products",
    },
  },
  {
    id: "05953408-d8f7-401b-9274-1e4c9c0f9c4b",
    slug: "fresh-orange",
    shop: {
      id: "8edf418b-4284-40db-bdc1-b2a0656be48e",
      slug: "anytime-buys",
      user: {
        id: "b6b4ebd5-2a35-40d3-ba3f-d91fbf17655e",
        email: "Elvis73@gmail.com",
        phone: "337-423-9407 x34711",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/766.jpg",
        password: "Xsh8gbmBxH1ThsY",
        dateOfBirth: "1978-11-20T22:00:28.358Z",
        verified: true,
        name: {
          firstName: "Sheridan",
          lastName: "Fay",
        },
      },
      email: "Juvenal13@yahoo.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Fresh Orange",
    brand: null,
    price: 164,
    size: null,
    colors: [],
    discount: 11,
    thumbnail: "/assets/images/Groceries Shop/Orange.png",
    images: [
      "/assets/images/Groceries Shop/Orange.png",
      "/assets/images/Groceries Shop/Orange.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "grocery-3",
      type: "top-saled-products",
    },
  },
];
