/* generated by JSetup ${JSetupVersion} :  at ${.now} */
package ${application.corePackage}.rs;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
@AllArgsConstructor
public class JsonOk {
	private final Serializable resp;
}
