/* generated by JSetup ${JSetupVersion} :  at ${.now} */
package ${application.corePackage}.rs;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
@AllArgsConstructor
public class DataUpload {
	private String dataType;
	private String dataUrl;
}
