<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by JSetup ${JSetupVersion} :  at ${.now}-->
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:tx="http://www.springframework.org/schema/tx" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:jaxrs="http://cxf.apache.org/jaxrs" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:aop="http://www.springframework.org/schema/aop" xmlns:jdbc="http://www.springframework.org/schema/jdbc" xmlns:websocket="http://www.springframework.org/schema/websocket" xmlns:mvc="http://www.springframework.org/schema/mvc"
	xsi:schemaLocation="
					http://www.springframework.org/schema/beans 
					http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
					http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.3.xsd
					http://cxf.apache.org/jaxrs
					http://cxf.apache.org/schemas/jaxrs.xsd
					http://www.springframework.org/schema/tx 
					http://www.springframework.org/schema/tx/spring-tx-4.3.xsd 
					http://www.springframework.org/schema/aop 
					http://www.springframework.org/schema/aop/spring-aop-4.3.xsd 
					http://www.springframework.org/schema/context  
					http://www.springframework.org/schema/context/spring-context-4.3.xsd
					http://www.springframework.org/schema/jdbc 
					http://www.springframework.org/schema/jdbc/spring-jdbc-4.3.xsd
					http://www.springframework.org/schema/websocket
        			http://www.springframework.org/schema/websocket/spring-websocket-4.3.xsd
        		    http://www.springframework.org/schema/mvc
        			http://www.springframework.org/schema/mvc/spring-mvc-4.3.xsd
        			 
					">
	<tx:annotation-driven />
	<mvc:annotation-driven />
	<context:annotation-config />
	<context:component-scan base-package="${application.rootPackage}" />
	<context:property-placeholder />
	
	<mvc:resources mapping="/login.html" location="/login.html" />
	<mvc:resources mapping="/vendor/**" location="/vendor/" />
	<mvc:resources mapping="/resources/**" location="/resources/" />
	<mvc:resources mapping="/applets/**" location="/applets/" />
	<mvc:resources mapping="/c/**" location="/c/" />
	<mvc:resources mapping="/css/**" location="/css/" />
	<mvc:resources mapping="/decorators/**" location="/decorators/" />
	<mvc:resources mapping="/downloads/**" location="/downloads/" />
	<mvc:resources mapping="/fonts/**" location="/fonts/" />
	<mvc:resources mapping="/sounds/**" location="/sounds/" />
	<mvc:resources mapping="/images/**" location="/images/" />
	<mvc:resources mapping="/javascript/**" location="/javascript/" />
	<mvc:resources mapping="/js/**" location="/js/" />
	<mvc:resources mapping="/j/**" location="/j/" />
	<mvc:resources mapping="/uploads/**" location="/uploads/" />

	<bean id="multipartResolver" class="org.springframework.web.multipart.commons.CommonsMultipartResolver">
		<property name="maxUploadSize" value="20971520" /> <!-- 20MB -->
		<property name="maxInMemorySize" value="1048576" /> <!-- 1MB -->
	</bean>
	
	<mvc:interceptors>
		<bean id="openSessionInViewInterceptor" class="org.springframework.orm.hibernate5.support.OpenSessionInViewInterceptor">
			<property name="sessionFactory" ref="sessionFactory" />
		</bean>
	</mvc:interceptors>

	<jdbc:initialize-database ignore-failures="ALL">
		<jdbc:script location="classpath:db/seed.sql" />
	</jdbc:initialize-database>

	<bean id="dataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource" destroy-method="close">
		<property name="driverClass" value="org.postgresql.Driver" />
		<property name="jdbcUrl" value="jdbc:postgresql://localhost:5432/db_${lowercase(application.appName)}" />
		<property name="user" value="postgres" />
		<property name="password" value="MasterKey@123" />

		<property name="acquireIncrement" value="10" />
		<property name="minPoolSize" value="10" />
		<property name="maxPoolSize" value="80" />
		<property name="maxIdleTime" value="200" />
	</bean>

	<bean id="transactionManager" class="org.springframework.orm.hibernate5.HibernateTransactionManager">
		<property name="sessionFactory" ref="sessionFactory" />
	</bean>

	<bean id="sessionFactory" class="org.springframework.orm.hibernate5.LocalSessionFactoryBean" scope="singleton">
		<property name="dataSource" ref="dataSource" />
		<property name="packagesToScan" value="${application.rootPackage}.model, ${application.corePackage}.model" />

		<property name="hibernateProperties">
			<props>
				<prop key="hibernate.dialect">org.hibernate.dialect.PostgreSQL82Dialect	</prop>
				<prop key="hibernate.format_sql">true</prop>
				<prop key="hibernate.show_sql">true</prop>
				<prop key="hibernate.hbm2ddl.auto">update</prop>
				<prop key="hibernate.transaction.flush_before_completion">true</prop>
			</props>
		</property>
	</bean>
	<bean id="afterThrow" class="${application.corePackage}.persistence.CatchThrowConstraintViolationException" />
	<bean class="org.springframework.aop.framework.autoproxy.BeanNameAutoProxyCreator">
		<property name="beanNames">
			<list>
				<value>*Service</value>
				<value>*ServiceImp</value>
			</list>
		</property>
		<property name="interceptorNames">
			<list>
				<value>afterThrow</value>
			</list>
		</property>
	</bean>
</beans>