/* generated by JSetup ${JSetupVersion} :  at ${.now} */
package ${application.rootPackage}.persistence;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import ${application.rootPackage}.model.${entity.name};
	
public interface ${entity.name}Repository extends JpaRepository<${entity.name}, Integer> ,JpaSpecificationExecutor<${entity.name}>{

}

//generated by JSetup ${JSetupVersion} :  at ${.now}