/* generated by JSetup ${JSetupVersion} :  at ${.now} */
package ${application.rootPackage}.service;

import java.util.List;
import org.apache.log4j.Logger;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.ArrayList;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.time.LocalDate;
<#if application.multitenancy>
import ${application.corePackage}.model.Tenant ;
</#if>

import ${application.rootPackage}.model.${entity.name};
import ${application.rootPackage}.persistence.${firstLower(entity.name)}Repository;
import ${application.rootPackage}.model.filter.Filter${entity.name};

import ${application.corePackage}.persistence.pagination.Pager;
import ${application.corePackage}.rs.exception.ValidationException;
import ${application.corePackage}.persistence.pagination.PaginationParams;
import ${application.corePackage}.utils.DateUtil;
import ${application.corePackage}.utils.Util;

@Service
@Transactional
public class ${entity.name}ServiceImp implements ${entity.name}Service {

	private static final Logger LOGGER = Logger.getLogger(${entity.name}ServiceImp.class);
	
	@Autowired
	${entity.name}Repository ${firstLower(entity.name)}Repository;
	
<#if application.multitenancy>
	public Optional<${entity.name}> get(Integer id, Tenant tenant) {
		return ${firstLower(entity.name)}Repository.findOne(${entity.name}SpecificationHelper.fromId(id, tenant));
	}

	public Pager<${entity.name}> get(SearchParameters<Filter${entity.name}> searchParams, Tenant tenant) {
		Filter${entity.name} filter = searchParams.getFilter();
		Pageable pageRequest = searchParams.getPageRequest();

		Page<${entity.name}> page = ${firstLower(entity.name)}Repository.findAll(${entity.name}SpecificationHelper.filter(filter, tenant), pageRequest);

		return new Pager<${entity.name}>(page.getContent(), page.getPageable().getPageNumber(), page.getTotalElements());
	}

	public Boolean delete(Integer id, Tenant tenant) {
		Optional<${entity.name}> optional = this.get(id, tenant);
		if (optional.isPresent()) {
			${firstLower(entity.name)}Repository.delete(optional.get());
		}
		return true;
	}
<#else>
	public Optional<${entity.name}> get(Integer id) {
		return ${firstLower(entity.name)}Repository.findOne(${entity.name}SpecificationHelper.fromId(id));
	}

	public Pager<${entity.name}> get(SearchParameters<Filter${entity.name}> searchParams) {
		Filter${entity.name} filter = searchParams.getFilter();
		Pageable pageRequest = searchParams.getPageRequest();

		Page<${entity.name}> page = ${firstLower(entity.name)}Repository.findAll(${entity.name}SpecificationHelper.filter(filter), pageRequest);

		return new Pager<${entity.name}>(page.getContent(), page.getPageable().getPageNumber(), page.getTotalElements());
	}
	
	public Boolean delete(Integer id) {
		Optional<${entity.name}> optional = this.get(id, tenant);
		if (optional.isPresent()) {
			${firstLower(entity.name)}Repository.delete(optional.get());
		}
		return true;
	}
</#if>

	public ${entity.name} save(${entity.name} entity) {
		return ${firstLower(entity.name)}Repository.save(entity);
	}

	public ${entity.name} update(${entity.name} entity) {
		return ${firstLower(entity.name)}Repository.save(entity);
	}
}

//generated by JSetup ${JSetupVersion} :  at ${.now}