/* generated by JSetup ${JSetupVersion} :  at ${.now} */
package ${package}.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
<#if application.multitenancy?? && application.multitenancy>
import ${application.corePackage}.model.Tenant;
</#if>
import ${application.rootPackage}.model.${entity.name};
import ${application.rootPackage}.model.filter.Filter${entity.name};

import ${application.corePackage}.persistence.pagination.Pager;
import ${application.corePackage}.persistence.pagination.SearchParameters;

public interface ${entity.name}Service {

<#if application.multitenancy?? &&  application.multitenancy && entity.multitenancy>
	public Optional<${entity.name}> get(Integer id, Tenant tenant) ;

	public Pager<${entity.name}> get(SearchParameters<Filter${entity.name}> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

    public ${entity.name} update(Integer id, Tenant tenant, ${entity.name} entity) ;
<#else>
	public Optional<${entity.name}> get(Integer id) ;

	public Pager<${entity.name}> get(SearchParameters<Filter${entity.name}> searchParams) ;
	
	public Boolean delete(Integer id);

	public ${entity.name} update(Integer id, ${entity.name} entity) ;
</#if>

	public ${entity.name} save(${entity.name} entity) ;
}
//generated by JSetup ${JSetupVersion} :  at ${.now}