export const categories = [
  {
    id: "4c9681ac-69e7-4ab6-b819-971b8ee9563b",
    name: "Birthday Gift",
    icon: null,
    image: "/assets/images/Gift Shop/Product 1.png",
    slug: "birthday-gift",
    parent: [],
    description: "27 Available Items",
    featured: true,
  },
  {
    id: "c8305a8a-a71e-4240-a01f-6b6336be20d9",
    name: "Couple Gift",
    icon: null,
    image: "/assets/images/Gift Shop/Product 2.png",
    slug: "couple-gift",
    parent: [],
    description: "17 Available Items",
    featured: true,
  },
  {
    id: "ce8d812a-1df6-4c00-84a0-e4ef9780adcd",
    name: "Baby Doll",
    icon: null,
    parent: [],
    slug: "baby-doll",
    description: "27 Available Items",
    image: "/assets/images/Gift Shop/Product 4.png",
    featured: false,
  },
  {
    id: "96c813a8-efff-4a51-8926-fc674757a135",
    name: "Men's Fashion",
    icon: null,
    image: "/assets/images/products/t-shirt4.png",
    slug: "men's-fashion",
    parent: [],
    description: null,
    featured: true,
  },
  {
    id: "76f4a1dd-fd27-461e-8b59-bfc3c1da6895",
    name: "Women's Fashion",
    icon: null,
    image: "/assets/images/products/t-shirt5.png",
    slug: "women's-fashion",
    parent: [],
    description: null,
    featured: false,
  },
  {
    id: "e6d2c2e3-d973-4367-98d8-0c140fbaf390",
    name: "Gadgets",
    icon: null,
    image: "/assets/images/products/smartwatch-2.png",
    slug: "gadgets",
    parent: [],
    description: null,
    featured: true,
  },
  {
    id: "f7b1da64-4d03-4a10-b364-67a2589b9de1",
    name: "Cosmatics",
    icon: null,
    image: "/assets/images/products/casmatics.jpg",
    slug: "cosmatics",
    parent: [],
    description: null,
    featured: true,
  },
];
