export const reviews = [
  {
    id: "d2e7dc64-578f-4732-97f8-d9893f167e53",
    rating: 5,
    customer: {
      id: "f4d769d6-a974-4d4f-aa29-6a3e8e2efcda",
      email: "Iliana.Bergstrom@yahoo.com",
      phone: "(803) 899-4000 x9513",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1227.jpg",
      password: "pll1ltX_68sSGp9",
      dateOfBirth: "1991-08-17T20:03:03.425Z",
      verified: true,
      name: {
        firstName: "Eladio",
        lastName: "Lehner",
      },
    },
    comment: "“But I must explain to you how all this of denouncing pleasure.”",
    product: {
      id: "dd63f47a-51a0-45f2-b9af-44190b87824f",
      slug: "smart-watch-black",
      shop: {
        id: "0aeb8359-c393-4cd0-a289-e24c06b1ee0c",
        slug: "constant-shoppers",
        user: {
          id: "c048d6ea-415a-42a0-891d-80c2230690d2",
          email: "Arnulfo82@gmail.com",
          phone: "(538) 223-6217 x46645",
          avatar:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/693.jpg",
          password: "1ua3CMPs0bptaDL",
          dateOfBirth: "1961-12-25T07:32:05.161Z",
          verified: true,
          name: {
            firstName: "Theodore",
            lastName: "Strosin",
          },
        },
        email: "Sasha_Windler@hotmail.com",
        name: "Constant Shoppers",
        phone: "(613) 343-9004",
        address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
        verified: false,
        coverPicture: "/assets/images/banners/banner-4.png",
        profilePicture: "/assets/images/faces/propic(3).png",
        socialLinks: {
          facebook: null,
          youtube: null,
          twitter: null,
          instagram: null,
        },
      },
      title: "Smart watch black",
      brand: null,
      price: 250,
      size: null,
      colors: [],
      discount: 25,
      thumbnail: "/assets/images/products/chair-and-clothes.png",
      images: [
        "/assets/images/products/chair-and-clothes.png",
        "/assets/images/products/chair-and-clothes.png",
        "/assets/images/products/chair-and-clothes.png",
      ],
      categories: [],
      status: null,
      reviews: [],
      rating: 4,
      unit: null,
    },
    published: true,
  },
  {
    id: "84bf3cf9-70d9-411a-856d-37a0763a71c3",
    rating: 5,
    customer: {
      id: "17d9dffd-ad46-4582-a05b-e68801f61df3",
      email: "Cecilia.Schimmel19@yahoo.com",
      phone: "680.325.5879 x708",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1197.jpg",
      password: "ntZfCFGwczb19XF",
      dateOfBirth: "1946-03-15T17:47:55.385Z",
      verified: true,
      name: {
        firstName: "Bruce",
        lastName: "Runolfsson",
      },
    },
    comment: "“But I must explain to you how all this of denouncing pleasure.”",
    product: {
      id: "d2baa1ce-968e-4bde-a073-f0bbf1cdb47b",
      slug: "asus-rog-strix-g15",
      shop: {
        id: "de15ade8-e00b-40dc-9b88-8ff29b410577",
        slug: "cybershop",
        user: {
          id: "c048d6ea-415a-42a0-891d-80c2230690d2",
          email: "Arnulfo82@gmail.com",
          phone: "(538) 223-6217 x46645",
          avatar:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/693.jpg",
          password: "1ua3CMPs0bptaDL",
          dateOfBirth: "1961-12-25T07:32:05.161Z",
          verified: true,
          name: {
            firstName: "Theodore",
            lastName: "Strosin",
          },
        },
        email: "Fabian.Strosin@yahoo.com",
        name: "Cybershop",
        phone: "(613) 343-9004",
        address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
        verified: false,
        coverPicture: "/assets/images/banners/banner-8.png",
        profilePicture: "/assets/images/faces/propic(7).png",
        socialLinks: {
          facebook: null,
          youtube: null,
          twitter: null,
          instagram: null,
        },
      },
      title: "ASUS ROG Strix G15",
      brand: null,
      price: 250,
      size: null,
      colors: [],
      discount: 56,
      thumbnail: "/assets/images/products/long-product.png",
      images: [
        "/assets/images/products/long-product.png",
        "/assets/images/products/long-product.png",
        "/assets/images/products/long-product.png",
      ],
      categories: [],
      status: null,
      reviews: [],
      rating: 4,
      unit: null,
    },
    published: true,
  },
  {
    id: "877942d8-e05c-4999-9660-73872505023e",
    rating: 5,
    customer: {
      id: "932bb26a-cf1d-4fbd-83aa-35324091bce1",
      email: "Trinity.Heaney94@gmail.com",
      phone: "1-251-928-6159",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/520.jpg",
      password: "R7_njHp4pQTB4hT",
      dateOfBirth: "1944-12-17T05:17:34.201Z",
      verified: true,
      name: {
        firstName: "Lucas",
        lastName: "Herzog",
      },
    },
    comment: "“But I must explain to you how all this of denouncing pleasure.”",
    product: {
      id: "ff1ef5ac-9019-4665-b452-bc246bac85cf",
      slug: "cafe-torrefaction-fraiche",
      shop: {
        id: "b24b914f-6c9a-467a-8b49-3d5b5b61d353",
        slug: "anytime-buys",
        user: {
          id: "c28bd1e5-9fec-4f2e-a06d-ff8b0c8fea9d",
          email: "Max_Skiles69@gmail.com",
          phone: "(966) 440-8893 x049",
          avatar:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/557.jpg",
          password: "i76Bwt1DQ6FkyVJ",
          dateOfBirth: "1953-11-01T00:40:47.762Z",
          verified: true,
          name: {
            firstName: "Lionel",
            lastName: "Reynolds",
          },
        },
        email: "Jade86@hotmail.com",
        name: "Anytime Buys",
        phone: "(613) 343-9004",
        address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
        verified: false,
        coverPicture: "/assets/images/banners/banner-6.png",
        profilePicture: "/assets/images/faces/propic(5).png",
        socialLinks: {
          facebook: null,
          youtube: null,
          twitter: null,
          instagram: null,
        },
      },
      title: "Cafe Torrefaction Fraiche",
      brand: null,
      price: 186,
      size: null,
      colors: [],
      discount: 10,
      thumbnail:
        "/assets/images/products/Groceries/25.CafeTorrefactionFraiche.png",
      images: [
        "/assets/images/products/Groceries/25.CafeTorrefactionFraiche.png",
        "/assets/images/products/Groceries/25.CafeTorrefactionFraiche.png",
        "/assets/images/products/Groceries/25.CafeTorrefactionFraiche.png",
      ],
      categories: ["groceries"],
      status: null,
      reviews: [],
      rating: 4,
      unit: null,
    },
    published: false,
  },
  {
    id: "5f0df38b-38d9-4ced-aa29-60ea132a9520",
    rating: 5,
    customer: {
      id: "17d9dffd-ad46-4582-a05b-e68801f61df3",
      email: "Cecilia.Schimmel19@yahoo.com",
      phone: "680.325.5879 x708",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1197.jpg",
      password: "ntZfCFGwczb19XF",
      dateOfBirth: "1946-03-15T17:47:55.385Z",
      verified: true,
      name: {
        firstName: "Bruce",
        lastName: "Runolfsson",
      },
    },
    comment: "“But I must explain to you how all this of denouncing pleasure.”",
    product: {
      id: "948f2ab6-73b3-46de-b2cd-f5ed554245ca",
      slug: "indian-copper-earrings",
      shop: {
        id: "3e8a8292-d600-4e6c-80bd-6a6badb73b0e",
        slug: "word-wide-wishes",
        user: {
          id: "066ddcec-71ed-44f0-9d51-6eb52c9757a0",
          email: "Nona_Koss@yahoo.com",
          phone: "1-805-374-6714",
          avatar:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/398.jpg",
          password: "5fQONJuwYKXixaP",
          dateOfBirth: "1958-03-09T03:07:12.221Z",
          verified: true,
          name: {
            firstName: "Nya",
            lastName: "Fahey",
          },
        },
        email: "Frida_Gislason@yahoo.com",
        name: "Word Wide Wishes",
        phone: "(613) 343-9004",
        address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
        verified: false,
        coverPicture: "/assets/images/banners/banner-7.png",
        profilePicture: "/assets/images/faces/propic(6).png",
        socialLinks: {
          facebook: null,
          youtube: null,
          twitter: null,
          instagram: null,
        },
      },
      title: "Indian Copper Earrings",
      brand: null,
      price: 181,
      size: null,
      colors: [],
      discount: 5,
      thumbnail:
        "/assets/images/products/Fashion/Jewellery/6.IndianCopperEarrings.png",
      images: [
        "/assets/images/products/Fashion/Jewellery/6.IndianCopperEarrings.png",
        "/assets/images/products/Fashion/Jewellery/6.IndianCopperEarrings.png",
        "/assets/images/products/Fashion/Jewellery/6.IndianCopperEarrings.png",
      ],
      categories: ["fashion"],
      status: null,
      reviews: [],
      rating: 5,
      unit: null,
    },
    published: true,
  },
  {
    id: "20a3bf95-6313-411d-a3c9-27c8dc34aae9",
    rating: 5,
    customer: {
      id: "f4d769d6-a974-4d4f-aa29-6a3e8e2efcda",
      email: "Iliana.Bergstrom@yahoo.com",
      phone: "(803) 899-4000 x9513",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1227.jpg",
      password: "pll1ltX_68sSGp9",
      dateOfBirth: "1991-08-17T20:03:03.425Z",
      verified: true,
      name: {
        firstName: "Eladio",
        lastName: "Lehner",
      },
    },
    comment: "“But I must explain to you how all this of denouncing pleasure.”",
    product: {
      id: "87639dfa-6513-4654-9efa-08746aa9398f",
      slug: "poland-full-set-v-drums",
      shop: {
        id: "7717a916-5b47-4a7b-a399-1ea148b96cac",
        slug: "keyboard-kiosk",
        user: {
          id: "84198285-078c-4b9c-9199-027d352d08d9",
          email: "Faustino.Greenholt@yahoo.com",
          phone: "245.384.3631 x4669",
          avatar:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/674.jpg",
          password: "CipXI2Yc3_dM0mS",
          dateOfBirth: "2002-01-04T21:59:19.280Z",
          verified: true,
          name: {
            firstName: "Easter",
            lastName: "Thiel",
          },
        },
        email: "Pearl86@hotmail.com",
        name: "Keyboard Kiosk",
        phone: "(613) 343-9004",
        address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
        verified: false,
        coverPicture: "/assets/images/banners/banner-5.png",
        profilePicture: "/assets/images/faces/propic(4).png",
        socialLinks: {
          facebook: null,
          youtube: null,
          twitter: null,
          instagram: null,
        },
      },
      title: "Poland Full Set V Drums",
      brand: null,
      price: 129,
      size: null,
      colors: [],
      discount: 7,
      thumbnail: "/assets/images/products/Music/25.RolandFullSetVDrums.png",
      images: [
        "/assets/images/products/Music/25.RolandFullSetVDrums.png",
        "/assets/images/products/Music/25.RolandFullSetVDrums.png",
        "/assets/images/products/Music/25.RolandFullSetVDrums.png",
      ],
      categories: ["music"],
      status: null,
      reviews: [],
      rating: 3,
      unit: null,
    },
    published: true,
  },
  {
    id: "ebc52608-5bbb-4ce5-8e8e-1d50d0e5c30d",
    rating: 5,
    customer: {
      id: "932bb26a-cf1d-4fbd-83aa-35324091bce1",
      email: "Trinity.Heaney94@gmail.com",
      phone: "1-251-928-6159",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/520.jpg",
      password: "R7_njHp4pQTB4hT",
      dateOfBirth: "1944-12-17T05:17:34.201Z",
      verified: true,
      name: {
        firstName: "Lucas",
        lastName: "Herzog",
      },
    },
    comment: "“But I must explain to you how all this of denouncing pleasure.”",
    product: {
      id: "d3538286-2d6d-4fb4-afe6-c5683844c140",
      slug: "beat-sw3",
      shop: {
        id: "b24b914f-6c9a-467a-8b49-3d5b5b61d353",
        slug: "anytime-buys",
        user: {
          id: "c28bd1e5-9fec-4f2e-a06d-ff8b0c8fea9d",
          email: "Max_Skiles69@gmail.com",
          phone: "(966) 440-8893 x049",
          avatar:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/557.jpg",
          password: "i76Bwt1DQ6FkyVJ",
          dateOfBirth: "1953-11-01T00:40:47.762Z",
          verified: true,
          name: {
            firstName: "Lionel",
            lastName: "Reynolds",
          },
        },
        email: "Jade86@hotmail.com",
        name: "Anytime Buys",
        phone: "(613) 343-9004",
        address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
        verified: false,
        coverPicture: "/assets/images/banners/banner-6.png",
        profilePicture: "/assets/images/faces/propic(5).png",
        socialLinks: {
          facebook: null,
          youtube: null,
          twitter: null,
          instagram: null,
        },
      },
      title: "beat sw3",
      brand: null,
      price: 121,
      size: null,
      colors: [],
      discount: 7,
      thumbnail: "/assets/images/products/Electronics/6.Sonya9.png",
      images: [
        "/assets/images/products/Electronics/6.Sonya9.png",
        "/assets/images/products/Electronics/6.Sonya9.png",
        "/assets/images/products/Electronics/6.Sonya9.png",
      ],
      categories: ["electronics"],
      status: null,
      reviews: [],
      rating: 4,
      unit: null,
    },
    published: false,
  },
  {
    id: "378d3b6c-39e6-4bf0-97c4-e5b63937ad62",
    rating: 5,
    customer: {
      id: "8d7dd5f7-cd1d-4050-ae7e-2b2ba11a66b3",
      email: "Lavon.Fadel@gmail.com",
      phone: "(554) 755-7712 x04946",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/952.jpg",
      password: "JaG33lUiR8R43jQ",
      dateOfBirth: "2001-03-01T06:50:46.060Z",
      verified: true,
      name: {
        firstName: "Audra",
        lastName: "Champlin",
      },
    },
    comment: "“But I must explain to you how all this of denouncing pleasure.”",
    product: {
      id: "dd63f47a-51a0-45f2-b9af-44190b87824f",
      slug: "smart-watch-black",
      shop: {
        id: "0aeb8359-c393-4cd0-a289-e24c06b1ee0c",
        slug: "constant-shoppers",
        user: {
          id: "c048d6ea-415a-42a0-891d-80c2230690d2",
          email: "Arnulfo82@gmail.com",
          phone: "(538) 223-6217 x46645",
          avatar:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/693.jpg",
          password: "1ua3CMPs0bptaDL",
          dateOfBirth: "1961-12-25T07:32:05.161Z",
          verified: true,
          name: {
            firstName: "Theodore",
            lastName: "Strosin",
          },
        },
        email: "Sasha_Windler@hotmail.com",
        name: "Constant Shoppers",
        phone: "(613) 343-9004",
        address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
        verified: false,
        coverPicture: "/assets/images/banners/banner-4.png",
        profilePicture: "/assets/images/faces/propic(3).png",
        socialLinks: {
          facebook: null,
          youtube: null,
          twitter: null,
          instagram: null,
        },
      },
      title: "Smart watch black",
      brand: null,
      price: 250,
      size: null,
      colors: [],
      discount: 25,
      thumbnail: "/assets/images/products/chair-and-clothes.png",
      images: [
        "/assets/images/products/chair-and-clothes.png",
        "/assets/images/products/chair-and-clothes.png",
        "/assets/images/products/chair-and-clothes.png",
      ],
      categories: [],
      status: null,
      reviews: [],
      rating: 4,
      unit: null,
    },
    published: true,
  },
  {
    id: "e3ab0d7b-a57b-4db2-a253-a6e135d9e0b6",
    rating: 5,
    customer: {
      id: "8d7dd5f7-cd1d-4050-ae7e-2b2ba11a66b3",
      email: "Lavon.Fadel@gmail.com",
      phone: "(554) 755-7712 x04946",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/952.jpg",
      password: "JaG33lUiR8R43jQ",
      dateOfBirth: "2001-03-01T06:50:46.060Z",
      verified: true,
      name: {
        firstName: "Audra",
        lastName: "Champlin",
      },
    },
    comment: "“But I must explain to you how all this of denouncing pleasure.”",
    product: {
      id: "5f47f8f7-1b5a-4a07-93f8-8cc528ee283e",
      slug: "lokia-android-one",
      shop: {
        id: "03c3e6fc-f3e5-470e-9cef-8257770f7249",
        slug: "coveted-clicks",
        user: {
          id: "96c9e925-91b3-4455-87f9-cdf908130997",
          email: "Sebastian.Brekke6@hotmail.com",
          phone: "(610) 386-7493 x582",
          avatar:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1054.jpg",
          password: "w82EID1rgaOCLYP",
          dateOfBirth: "1958-07-06T02:38:50.960Z",
          verified: true,
          name: {
            firstName: "Cathryn",
            lastName: "Rippin",
          },
        },
        email: "Gudrun20@gmail.com",
        name: "Coveted Clicks",
        phone: "(613) 343-9004",
        address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
        verified: false,
        coverPicture: "/assets/images/banners/banner-3.png",
        profilePicture: "/assets/images/faces/propic(2).png",
        socialLinks: {
          facebook: null,
          youtube: null,
          twitter: null,
          instagram: null,
        },
      },
      title: "Lokia android one",
      brand: null,
      price: 122,
      size: null,
      colors: [],
      discount: 9,
      thumbnail: "/assets/images/products/Electronics/30.Nokiaandroidone.png",
      images: [
        "/assets/images/products/Electronics/30.Nokiaandroidone.png",
        "/assets/images/products/Electronics/30.Nokiaandroidone.png",
        "/assets/images/products/Electronics/30.Nokiaandroidone.png",
      ],
      categories: ["electronics"],
      status: null,
      reviews: [],
      rating: 4,
      unit: null,
    },
    published: false,
  },
];
