package ${application.corePackage}.serialization;

import java.io.IOException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
/** generated by JSetup ${JSetupVersion} :  at ${.now}  */
public class CustomSyncObjectIdDeserializer extends JsonDeserializer<Integer> {

	private static final Logger LOGGER = Logger.LoggerFactory(CustomSyncObjectIdDeserializer.class);

	@Override
	public Integer deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {

		String idInter = jp.getText();
		try {
			return Integer.parseInt(idInter);
		} catch (Exception e) {
			LOGGER.warn("Erro ao deserializar dataInter: " + idInter);
		}
		return null;
	}
}